cask "font-mona-sans" do
  version "2.0"
  sha256 "7e4ea90d0a3b7f355a6e369eeaa72f07e6510f59596910d02587f8ea7249b94c"

  url "https:github.comgithubmona-sansreleasesdownloadv#{version}MonaSans.zip"
  name "Mona Sans"
  homepage "https:github.commona-sans"

  no_autobump! because: :requires_manual_review

  font "MonaSansOTFMonaSans-Black.otf"
  font "MonaSansOTFMonaSans-BlackItalic.otf"
  font "MonaSansOTFMonaSans-Bold.otf"
  font "MonaSansOTFMonaSans-BoldItalic.otf"
  font "MonaSansOTFMonaSans-ExtraBold.otf"
  font "MonaSansOTFMonaSans-ExtraBoldItalic.otf"
  font "MonaSansOTFMonaSans-ExtraLight.otf"
  font "MonaSansOTFMonaSans-ExtraLightItalic.otf"
  font "MonaSansOTFMonaSans-Italic.otf"
  font "MonaSansOTFMonaSans-Light.otf"
  font "MonaSansOTFMonaSans-LightItalic.otf"
  font "MonaSansOTFMonaSans-Medium.otf"
  font "MonaSansOTFMonaSans-MediumItalic.otf"
  font "MonaSansOTFMonaSans-Regular.otf"
  font "MonaSansOTFMonaSans-SemiBold.otf"
  font "MonaSansOTFMonaSans-SemiBoldItalic.otf"
  font "MonaSansOTFMonaSansCondensed-Black.otf"
  font "MonaSansOTFMonaSansCondensed-BlackItalic.otf"
  font "MonaSansOTFMonaSansCondensed-Bold.otf"
  font "MonaSansOTFMonaSansCondensed-BoldItalic.otf"
  font "MonaSansOTFMonaSansCondensed-ExtraBold.otf"
  font "MonaSansOTFMonaSansCondensed-ExtraBoldItalic.otf"
  font "MonaSansOTFMonaSansCondensed-ExtraLight.otf"
  font "MonaSansOTFMonaSansCondensed-ExtraLightItalic.otf"
  font "MonaSansOTFMonaSansCondensed-Italic.otf"
  font "MonaSansOTFMonaSansCondensed-Light.otf"
  font "MonaSansOTFMonaSansCondensed-LightItalic.otf"
  font "MonaSansOTFMonaSansCondensed-Medium.otf"
  font "MonaSansOTFMonaSansCondensed-MediumItalic.otf"
  font "MonaSansOTFMonaSansCondensed-Regular.otf"
  font "MonaSansOTFMonaSansCondensed-SemiBold.otf"
  font "MonaSansOTFMonaSansCondensed-SemiBoldItalic.otf"
  font "MonaSansOTFMonaSansExpanded-Black.otf"
  font "MonaSansOTFMonaSansExpanded-BlackItalic.otf"
  font "MonaSansOTFMonaSansExpanded-Bold.otf"
  font "MonaSansOTFMonaSansExpanded-BoldItalic.otf"
  font "MonaSansOTFMonaSansExpanded-ExtraBold.otf"
  font "MonaSansOTFMonaSansExpanded-ExtraBoldItalic.otf"
  font "MonaSansOTFMonaSansExpanded-ExtraLight.otf"
  font "MonaSansOTFMonaSansExpanded-ExtraLightItalic.otf"
  font "MonaSansOTFMonaSansExpanded-Italic.otf"
  font "MonaSansOTFMonaSansExpanded-Light.otf"
  font "MonaSansOTFMonaSansExpanded-LightItalic.otf"
  font "MonaSansOTFMonaSansExpanded-Medium.otf"
  font "MonaSansOTFMonaSansExpanded-MediumItalic.otf"
  font "MonaSansOTFMonaSansExpanded-Regular.otf"
  font "MonaSansOTFMonaSansExpanded-SemiBold.otf"
  font "MonaSansOTFMonaSansExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end