cask "font-mona-sans" do
  version "1.0.1"
  sha256 "c5e44e736b72bbbd47ae7fecfde8f0c149ba2c0a436d27a2f1ec6392ba3ecd0b"

  url "https:github.comgithubmona-sansreleasesdownloadv#{version}MonaSans.zip"
  name "Mona Sans"
  homepage "https:github.commona-sans"

  font "Mona SansOTFMonaSans-Black.otf"
  font "Mona SansOTFMonaSans-BlackItalic.otf"
  font "Mona SansOTFMonaSans-Bold.otf"
  font "Mona SansOTFMonaSans-BoldItalic.otf"
  font "Mona SansOTFMonaSans-ExtraBold.otf"
  font "Mona SansOTFMonaSans-ExtraBoldItalic.otf"
  font "Mona SansOTFMonaSans-ExtraLight.otf"
  font "Mona SansOTFMonaSans-ExtraLightItalic.otf"
  font "Mona SansOTFMonaSans-Italic.otf"
  font "Mona SansOTFMonaSans-Light.otf"
  font "Mona SansOTFMonaSans-LightItalic.otf"
  font "Mona SansOTFMonaSans-Medium.otf"
  font "Mona SansOTFMonaSans-MediumItalic.otf"
  font "Mona SansOTFMonaSans-Regular.otf"
  font "Mona SansOTFMonaSans-SemiBold.otf"
  font "Mona SansOTFMonaSans-SemiBoldItalic.otf"
  font "Mona SansOTFMonaSansCondensed-Black.otf"
  font "Mona SansOTFMonaSansCondensed-BlackItalic.otf"
  font "Mona SansOTFMonaSansCondensed-Bold.otf"
  font "Mona SansOTFMonaSansCondensed-BoldItalic.otf"
  font "Mona SansOTFMonaSansCondensed-ExtraBold.otf"
  font "Mona SansOTFMonaSansCondensed-ExtraBoldItalic.otf"
  font "Mona SansOTFMonaSansCondensed-ExtraLight.otf"
  font "Mona SansOTFMonaSansCondensed-ExtraLightItalic.otf"
  font "Mona SansOTFMonaSansCondensed-Italic.otf"
  font "Mona SansOTFMonaSansCondensed-Light.otf"
  font "Mona SansOTFMonaSansCondensed-LightItalic.otf"
  font "Mona SansOTFMonaSansCondensed-Medium.otf"
  font "Mona SansOTFMonaSansCondensed-MediumItalic.otf"
  font "Mona SansOTFMonaSansCondensed-Regular.otf"
  font "Mona SansOTFMonaSansCondensed-SemiBold.otf"
  font "Mona SansOTFMonaSansCondensed-SemiBoldItalic.otf"
  font "Mona SansOTFMonaSansExpanded-Black.otf"
  font "Mona SansOTFMonaSansExpanded-BlackItalic.otf"
  font "Mona SansOTFMonaSansExpanded-Bold.otf"
  font "Mona SansOTFMonaSansExpanded-BoldItalic.otf"
  font "Mona SansOTFMonaSansExpanded-ExtraBold.otf"
  font "Mona SansOTFMonaSansExpanded-ExtraBoldItalic.otf"
  font "Mona SansOTFMonaSansExpanded-ExtraLight.otf"
  font "Mona SansOTFMonaSansExpanded-ExtraLightItalic.otf"
  font "Mona SansOTFMonaSansExpanded-Italic.otf"
  font "Mona SansOTFMonaSansExpanded-Light.otf"
  font "Mona SansOTFMonaSansExpanded-LightItalic.otf"
  font "Mona SansOTFMonaSansExpanded-Medium.otf"
  font "Mona SansOTFMonaSansExpanded-MediumItalic.otf"
  font "Mona SansOTFMonaSansExpanded-Regular.otf"
  font "Mona SansOTFMonaSansExpanded-SemiBold.otf"
  font "Mona SansOTFMonaSansExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end