require "languagenode"

class Json2ts < Formula
  desc "Compile JSONSchema to TypeScript type declarations"
  homepage "https:github.combchernyjson-schema-to-typescript"
  url "https:registry.npmjs.orgjson-schema-to-typescript-json-schema-to-typescript-14.0.5.tgz"
  sha256 "304e0a675ed06361797c9b9c6fbb7163bd70cf4085db0eab7676e5eea2cf974f"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "e915354b849da5a0575f960aa3ec34b080f1d7de0e3b4e6c40ca565033f1dbb5"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "e915354b849da5a0575f960aa3ec34b080f1d7de0e3b4e6c40ca565033f1dbb5"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "e915354b849da5a0575f960aa3ec34b080f1d7de0e3b4e6c40ca565033f1dbb5"
    sha256 cellar: :any_skip_relocation, sonoma:         "cd69658ebb79c6bd8c9c95b0f3b0b20b76cebe5a7956e768a694c105d3ead61c"
    sha256 cellar: :any_skip_relocation, ventura:        "cd69658ebb79c6bd8c9c95b0f3b0b20b76cebe5a7956e768a694c105d3ead61c"
    sha256 cellar: :any_skip_relocation, monterey:       "cd69658ebb79c6bd8c9c95b0f3b0b20b76cebe5a7956e768a694c105d3ead61c"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "b09028f1a0aa1aa01afb68ca54fe164fdaed7f1c1124d63bc7b80dfc75c46d53"
  end

  depends_on "node"

  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}bin*"]
  end

  test do
    schema = <<~JSON
      {
        "title": "Example Schema",
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "age": {
            "description": "Age in years",
            "type": "integer",
            "minimum": 0
          },
          "hairColor": {
            "enum": ["black", "brown", "blue"],
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": ["firstName", "lastName"]
      }
    JSON

    typescript = <<~TS
      * eslint-disable *
      **
       * This file was automatically generated by json-schema-to-typescript.
       * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
       * and run json-schema-to-typescript to regenerate this file.
       *

      export interface ExampleSchema {
        firstName: string;
        lastName: string;
        **
         * Age in years
         *
        age?: number;
        hairColor?: "black" | "brown" | "blue";
      }
    TS

    output = pipe_output("#{bin}json2ts", schema)
    assert_equal output, typescript
  end
end