class Mockolo < Formula
  desc "Efficient Mock Generator for Swift"
  homepage "https://github.com/uber/mockolo"
  url "https://ghfast.top/https://github.com/uber/mockolo/archive/refs/tags/2.7.0.tar.gz"
  sha256 "43b8dba76938b4d86df0e3e40be46211a2ea1616a17e87553248dd27e7cec045"
  license "Apache-2.0"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "7c2a52cf72ef0ad4e787b564358e27f925fb2db6201b2facf765766176a32c54"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "9d8670e2a919766ae8a3c047aacda18bbb77bbf6b9609073cbbc9c659372ab7b"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "7c9b24b30ebfd69eab92c1b7250c4e31c16730e615c1529448119a0ec8751781"
    sha256 cellar: :any,                 arm64_linux:       "2a198131e0f6e738c750d91b3e9ed9bc70937087986005241d3e57724589732e"
    sha256 cellar: :any,                 x86_64_linux:      "8ec480bff40b0a277261adbc438f4c621809d713a849fff248538217e50510b2"
  end

  uses_from_macos "swift" => :build

  on_macos do
    depends_on xcode: ["15.3", :build]
  end

  deny_network_access!

  def fetch
    # SwiftPM tries to apply its own sandbox, which cannot nest inside the
    # build sandbox; Homebrew's sandbox still confines the whole process.
    system "swift", "package", "resolve", "--disable-sandbox"
  end

  def install
    inreplace "Sources/Mockolo/Version.swift", "development", version.to_s
    system "swift", "build", "--product", "mockolo", *std_swift_args
    bin.install ".build/release/mockolo"
    generate_completions_from_executable(bin/"mockolo", "--generate-completion-script")
  end

  test do
    (testpath/"testfile.swift").write <<~SWIFT
      /// @mockable
      public protocol Foo {
          var num: Int { get set }
          func bar(arg: Float) -> String
      }
    SWIFT
    system bin/"mockolo", "-srcs", testpath/"testfile.swift", "-d", testpath/"GeneratedMocks.swift"
    assert_path_exists testpath/"GeneratedMocks.swift"
    output = <<~SWIFT.gsub(/\s+/, "").strip
      ///
      /// @Generated by Mockolo
      ///
      public class FooMock: Foo {
        public init() { }
        public init(num: Int = 0) {
            self.num = num
        }

        public private(set) var numSetCallCount = 0
        public var num: Int = 0 { didSet { numSetCallCount += 1 } }

        public private(set) var barCallCount = 0
        public var barHandler: ((Float) -> String)?
        public func bar(arg: Float) -> String {
            barCallCount += 1
            if let barHandler = barHandler {
                return barHandler(arg)
            }
            return ""
        }
      }
    SWIFT
    assert_equal output, shell_output("cat #{testpath/"GeneratedMocks.swift"}").gsub(/\s+/, "").strip
  end
end