class Scdoc < Formula
  desc "Small man page generator"
  homepage "https://sr.ht/~sircmpwn/scdoc/"
  url "https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.5.tar.gz"
  sha256 "98780bbdf16c1bce89ef3a8c0f537ac6e4ea77087b609e7698857614488a2a62"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "802dc7fb1272bca537c94246e9cb406b33ab390e7d204e91e6b0dc6658fd83f7"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "d8e173d57296622ceb431df136c5501120ab1242864cf83be9f002be73286bf7"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "45fb8e2a4c7db5b1e60416f7fad538447615cee2f25a1410a46a5e9b2f058ca3"
    sha256 cellar: :any_skip_relocation, sonoma:        "c3957906c60806e61b4bc8180998aaa6ce2b1b7725bfc0b92913e6bd57f4e2d7"
    sha256 cellar: :any,                 arm64_linux:   "3d4f870fdf7f9d90e57b5a904a9468d8fc81230ce3fad13a7cabe0a19647c5be"
    sha256 cellar: :any,                 x86_64_linux:  "e88f2ac7bdd4068537a251a3b91de6eb69c0a93ea76b549755f04836dcffb7b5"
  end

  def install
    # scdoc sets by default LDFLAGS=-static which doesn't work on macos(x)
    system "make", "LDFLAGS=#{ENV.ldflags}", "PREFIX=#{prefix}"
    system "make", "install", "PREFIX=#{prefix}"
  end

  test do
    preamble = <<~EOF
      .\\" Generated by scdoc #{version}
      .\\" Complete documentation for this program is not available as a GNU info page
      .ie \\n(.g .ds Aq \\(aq
      .el       .ds Aq '
      .nh
      .ad l
      .\\" Begin generated content:
    EOF
    assert_equal preamble, pipe_output(bin/"scdoc", "")
  end
end