class Sqlc < Formula
  desc "Generate type safe Go from SQL"
  homepage "https://sqlc.dev/"
  url "https://ghproxy.com/https://github.com/sqlc-dev/sqlc/archive/refs/tags/v1.22.0.tar.gz"
  sha256 "858846f4c1f0ee49d20caa1cdcc0b5d7e1c41c79fa5e2091811451b69dd7c8dc"
  license "MIT"
  head "https://github.com/sqlc-dev/sqlc.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "d7185768dd63e1f2d64567caf22c71ca7b77160cd9a478e343bde200243fcf11"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "d2c95be3f2f92032b53664ba3c1b160b1478be30fdbb65f3ca5901f48fd36930"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "c45eff9c3aa7df7123058ef11dc10a0e47bc15675dadb1eefec749a2ded9861d"
    sha256 cellar: :any_skip_relocation, sonoma:         "de75afd757482afa9ffa7f6bab2334b21adac99e00b43024d46d04e16c699afb"
    sha256 cellar: :any_skip_relocation, ventura:        "5c943a6fd7683e79752e67a6c877729545072d18897a7543682acb91033115c2"
    sha256 cellar: :any_skip_relocation, monterey:       "22cfea89e6dad27d8a7714c066eb2eb8c09a1076c1ca50bd9a0708a4bdb6bc3c"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "58fbfaf55efd9caf39ff8973947d92121e4f8728c4447050cdb85f4ffe252ed8"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/sqlc"

    generate_completions_from_executable(bin/"sqlc", "completion")
  end

  test do
    (testpath/"sqlc.json").write <<~SQLC
      {
        "version": "1",
        "packages": [
          {
            "name": "db",
            "path": ".",
            "queries": "query.sql",
            "schema": "query.sql",
            "engine": "postgresql"
          }
        ]
      }
    SQLC

    (testpath/"query.sql").write <<~EOS
      CREATE TABLE foo (bar text);

      -- name: SelectFoo :many
      SELECT * FROM foo;
    EOS

    system bin/"sqlc", "generate"
    assert_predicate testpath/"db.go", :exist?
    assert_predicate testpath/"models.go", :exist?
    assert_match "// Code generated by sqlc. DO NOT EDIT.", File.read(testpath/"query.sql.go")
  end
end