class Sqlc < Formula
  desc "Generate type safe Go from SQL"
  homepage "https://sqlc.dev/"
  url "https://ghproxy.com/https://github.com/sqlc-dev/sqlc/archive/refs/tags/v1.23.0.tar.gz"
  sha256 "29171425b68bf5ca99c0fd7fd2107e087fec17778f56493d952c03b3b84d2913"
  license "MIT"
  head "https://github.com/sqlc-dev/sqlc.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "b8703d9aaad5bb01ea5753ba2056dad918d1621871c9074b8ca2b15613765c30"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "742c83b3218adb7cca7d56be8758d9a6c130020d2592cffe508a82408edda99d"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "e5f58eb33b64cbc0ed8836324be9b00030e09f0c862cfcc139d4bad63b4ebf28"
    sha256 cellar: :any_skip_relocation, sonoma:         "9725688a254d0804a104eb226cff7662216966e5ca8bfb60377297af0177a39c"
    sha256 cellar: :any_skip_relocation, ventura:        "79e58390b92c8937ab8fd110681690a700ad7a7b905382fe114f7ed582345d7f"
    sha256 cellar: :any_skip_relocation, monterey:       "8dcef7c94fdaa121e11b2bb4e3a6d23b00b718e343faff3a0f79279485cbfaf6"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "7a1d2409c3078a1b36826fb14a11fe044b4cc5d0e1652a97b31083eb2c228eaf"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/sqlc"

    generate_completions_from_executable(bin/"sqlc", "completion")
  end

  test do
    (testpath/"sqlc.json").write <<~SQLC
      {
        "version": "1",
        "packages": [
          {
            "name": "db",
            "path": ".",
            "queries": "query.sql",
            "schema": "query.sql",
            "engine": "postgresql"
          }
        ]
      }
    SQLC

    (testpath/"query.sql").write <<~EOS
      CREATE TABLE foo (bar text);

      -- name: SelectFoo :many
      SELECT * FROM foo;
    EOS

    system bin/"sqlc", "generate"
    assert_predicate testpath/"db.go", :exist?
    assert_predicate testpath/"models.go", :exist?
    assert_match "// Code generated by sqlc. DO NOT EDIT.", File.read(testpath/"query.sql.go")
  end
end