class Fig2dev < Formula
  desc "Translates figures generated by xfig to other formats"
  homepage "https://mcj.sourceforge.net/"
  url "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9a.tar.xz"
  sha256 "61e185393176852f03b901b3b05b19fbc5ad8258ff142f3da6e70b1b83513326"
  license "MIT"

  livecheck do
    url :stable
    regex(%r{url=.*?/fig2dev[._-]v?(\d+(?:\.\d+)+[a-z]?)\.t}i)
  end

  bottle do
    rebuild 1
    sha256 arm64_tahoe:   "24dd6f6aa035586bd4c43d727b1329b822da452a0f64005a9defa12f2fa0faed"
    sha256 arm64_sequoia: "3d512815be04dc846c43c7545cc14789388a7840c79e8ad32a577c8c684d4e8e"
    sha256 arm64_sonoma:  "d0d35f3dab34be63355f01fa4ab890e2717aefb06f9746743e1643bf3bcba6b2"
    sha256 sonoma:        "f5c02dd6fc06b3a6a1c4ba2bf18092557333e0c71c44d07d096f5b55351a545a"
    sha256 arm64_linux:   "283acf4bd2ad10d9129183b890593d493f10fbefc264ea7c1976ae3acd7a931e"
    sha256 x86_64_linux:  "33f3779d09912197a0591a8e94c6c8906726982c38cf7f9adbe0ec3222ab8d66"
  end

  depends_on "ghostscript"
  depends_on "libpng"
  depends_on "netpbm"

  on_linux do
    depends_on "zlib-ng-compat"
  end

  def install
    system "./configure", "--enable-transfig",
            *std_configure_args.reject { |s| s["--disable-debug"] }
    system "make", "install"

    pkgshare.install "fig2dev/tests/data/patterns.fig"
  end

  test do
    system bin/"fig2dev", "-L", "png", "#{pkgshare}/patterns.fig", "patterns.png"
    assert_path_exists testpath/"patterns.png", "Failed to create PNG"
  end
end