class Fig2dev < Formula
  desc "Translates figures generated by xfig to other formats"
  homepage "https://mcj.sourceforge.net/"
  url "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.9.tar.xz"
  sha256 "15e246c8d13cc72de25e08314038ad50ce7d2defa9cf1afc172fd7f5932090b1"
  license "MIT"

  livecheck do
    url :stable
    regex(%r{url=.*?/fig2dev[._-]v?(\d+(?:\.\d+)+[a-z]?)\.t}i)
  end

  bottle do
    sha256 arm64_sequoia:  "8f173110cd35df498c9d4297ae73fc5d46a9dcdd65f36b5551c75f70fb839b72"
    sha256 arm64_sonoma:   "6269b97dcb35b0fa282b40f3b58c7851feafdb947f8f0119333054a5605bae76"
    sha256 arm64_ventura:  "f8fbe5bb954be25f1c4160c0b2c0a021568dabee8e9df8e0039c161476f0a840"
    sha256 arm64_monterey: "26ed11b4a0ee2a8f4f89838165814985efa9bd05aca297ec49b43c7defd3370a"
    sha256 arm64_big_sur:  "fd3f9e74f89227f96ff7a3845ece61e8a5450a594756d526cbdb178d94c9f744"
    sha256 sonoma:         "158e0eeef207c3a042f83aaafc50a271fbd92dfa498f67486a4f8c263d3d77ee"
    sha256 ventura:        "c07fa30415efdaf63b992e5692277eb95994ef7e332cbedbf8df54097ab6646e"
    sha256 monterey:       "6e0bcd2884195db2454d9c6dc12c2a5823e43d98f2ced907263bc290068d3f4f"
    sha256 big_sur:        "64c9f0750199f820695b1924e199b2547286a3373872e0d2b2af6e58b16edac5"
    sha256 x86_64_linux:   "967bc57906acb428eba4ad89d47a1b9ecfeef8c3f2589f8e9de1eaa94fe3eb3d"
  end

  depends_on "ghostscript"
  depends_on "libpng"
  depends_on "netpbm"

  def install
    args = %W[
      --prefix=#{prefix}
      --disable-dependency-tracking
      --disable-silent-rules
      --enable-transfig
      --without-xpm
      --without-x
    ]

    system "./configure", *args
    system "make", "install"

    # Install a fig file for testing
    pkgshare.install "fig2dev/tests/data/patterns.fig"
  end

  test do
    system bin/"fig2dev", "-L", "png", "#{pkgshare}/patterns.fig", "patterns.png"
    assert_predicate testpath/"patterns.png", :exist?, "Failed to create PNG"
  end
end