class AddDeterminism < Formula
  desc "Build postprocessor to reset metadata fields for build reproducibility"
  homepage "https://github.com/keszybz/add-determinism"
  url "https://ghfast.top/https://github.com/keszybz/add-determinism/archive/refs/tags/v0.7.3.tar.gz"
  sha256 "d1f5eac303807fa31e25b4f8ccb08fed23d15f4ffdbe3bb4ee35a29504c766b2"
  license "GPL-3.0-or-later"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "a4acaeccbe7f1e8390d00e81f85104468a061865aa885de7bd2c5980583d47ca"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "ca533c86ffccf0438b6498f38fc7ec05fd10bb74bb8afeaef4a22f378ca6eb42"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "913e2ae4671e6be498e000325049cbe2637b2f6ebb480e8ff12a174132e61325"
    sha256 cellar: :any_skip_relocation, sonoma:        "4a6e9027ec99269def2d6823502b933e3290ab59fd64003cb68ce3836d0d65a0"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "f81478dd7b06b5f7d120447e2552aad28a48edb0ac53c77d402137d27ecbc6f2"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "e38dcf219d4522e98b3b313c830f480c0bc318fa8243b0586e7053cde7691aac"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "llvm" => :build

  on_linux do
    depends_on "libselinux"
    depends_on "zlib-ng-compat"
  end

  def install
    ENV["RUSTFLAGS"] = "-C link-arg=-lselinux" if OS.linux?
    system "cargo", "install", *std_cargo_args
  end

  test do
    (testpath/"test.html").write <<~HTML
      <!-- Generated by javadoc (1.2.3) on 2025-01-01 -->
      <meta name="dc.created" content="2025-01-01">
    HTML

    ENV["SOURCE_DATE_EPOCH"] = "0"
    system bin/"add-det", testpath/"test.html"

    assert_match "<!-- Generated by javadoc -->", (testpath/"test.html").read
    assert_match "content=\"1970-01-01\"", (testpath/"test.html").read
  end
end