class AsTree < Formula
  desc "Print a list of paths as a tree of paths"
  homepage "https://github.com/jez/as-tree"
  url "https://ghfast.top/https://github.com/jez/as-tree/archive/refs/tags/0.12.0.tar.gz"
  sha256 "2af03a2b200041ac5c7a20aa1cea0dcc21fb83ac9fe9a1cd63cb02adab299456"
  license "BlueOak-1.0.0"

  bottle do
    rebuild 1
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "8563658ddfac98fa9b2cfa8174c6ac573b024fdefa33b705a356efd5c432eecb"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "21036f05ea5294ef3b8f2fb17517631a76c8d2c2ed521311322a55ba2320a28e"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "5059a4f64cd775588b4f57a258964415373c09346d65f121f9e61464bbc6789a"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:      "c54dc2d8c4eb0848cf008d1aba865d566d31a711fcba898e06d50553f14e4720"
    sha256 cellar: :any_skip_relocation, arm64_ventura:     "f1ff59d33ae1147f903973d50d44e945b7d4ef2564d8877be6fc38b9433bafb6"
    sha256 cellar: :any_skip_relocation, arm64_monterey:    "7ffe542490373f69918fbb37ef7e93c94a7d26e87f4be282b491816713b7d049"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:     "4cbe38f0537c86b65808064608c61b8c792098177911f013f24c2470fd2fdf62"
    sha256 cellar: :any_skip_relocation, sonoma:            "a5a2de8891810abc35ac5c0815003aac603e9467633eaebe161a71e8ccc5dadd"
    sha256 cellar: :any_skip_relocation, ventura:           "427e9bc1f7f6a92da07ad4284e82ab6b3d24441bac2c0f5b4850c250106622b6"
    sha256 cellar: :any_skip_relocation, monterey:          "adf2bb6e9bbbcc4d393462ec04b4cf9abe28bc5748f9636b0a9668b56082fb60"
    sha256 cellar: :any_skip_relocation, big_sur:           "2d13c83015f82b0b39760b9087f417bc1465b4e33cc6a90061235a70e510c896"
    sha256 cellar: :any_skip_relocation, arm64_linux:       "0c877d85a4310115448ce71c13d75b93976ee2bea0b0ef0e890c53a469e8f85d"
    sha256 cellar: :any_skip_relocation, x86_64_linux:      "82337903e0b8ee48cd19517b4d1bd8e0b66d5c17e212a03f6e15d2b12130d85b"
  end

  # Last commit was 5 years ago and requires patches
  deprecate! date: "2026-10-02", because: :unmaintained
  disable! date: "2027-10-02", because: :unmaintained

  depends_on "rust" => :build

  # Update lockfile
  patch :DATA

  deny_network_access!

  def fetch
    system "cargo", "fetch", *std_cargo_fetch_args
  end

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_equal ".\n└── file\n", pipe_output(bin/"as-tree", "file", 0)
  end
end

__END__
diff --git a/Cargo.lock b/Cargo.lock
index 991ecd8..bdb9067 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1,5 +1,7 @@
 # This file is automatically @generated by Cargo.
 # It is not intended for manual editing.
+version = 4
+
 [[package]]
 name = "ansi_term"
 version = "0.12.1"
@@ -11,7 +13,7 @@ dependencies = [
 
 [[package]]
 name = "as-tree"
-version = "0.11.1"
+version = "0.12.0"
 dependencies = [
  "ansi_term",
  "atty",
@@ -31,33 +33,33 @@ dependencies = [
 
 [[package]]
 name = "hermit-abi"
-version = "0.1.12"
+version = "0.1.19"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "61565ff7aaace3525556587bd2dc31d4a07071957be715e63ce7b1eccf51a8f4"
+checksum = "62b467343b94ba476dcb2500d242dadbb39557df889310ac77c5d99100aaac33"
 dependencies = [
  "libc",
 ]
 
 [[package]]
 name = "libc"
-version = "0.2.70"
+version = "0.2.189"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "3baa92041a6fec78c687fa0cc2b3fae8884f743d672cf551bed1d6dac6988d0f"
+checksum = "3eaf3ede3fee6db1a4c2ee091bf8a8b4dccdc6d17f656fb07896ee72867612f2"
 
 [[package]]
 name = "lscolors"
-version = "0.7.0"
+version = "0.7.1"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "1f77452267149eac960ded529fe5f5460ddf792845a1d71b5d0cfcee5642e47e"
+checksum = "d24b894c45c9da468621cdd615a5a79ee5e5523dd4f75c76ebc03d458940c16e"
 dependencies = [
  "ansi_term",
 ]
 
 [[package]]
 name = "winapi"
-version = "0.3.8"
+version = "0.3.9"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "8093091eeb260906a183e6ae1abdba2ef5ef2257a21801128899c3fc699229c6"
+checksum = "5c839a674fcd7a98952e593242ea400abe93992746761e38641405d28b00f419"
 dependencies = [
  "winapi-i686-pc-windows-gnu",
  "winapi-x86_64-pc-windows-gnu",