class PipTools < Formula
  include Language::Python::Virtualenv

  desc "Locking and sync for Pip requirements files"
  homepage "https://pip-tools.readthedocs.io"
  url "https://files.pythonhosted.org/packages/08/40/8c1b0384f1cc7df50b7af97620038f3bf6ccaf0973db6cd5d965b5b2a97e/pip-tools-7.4.0.tar.gz"
  sha256 "a92a6ddfa86ff389fe6ace381d463bc436e2c705bd71d52117c25af5ce867bb7"
  license "BSD-3-Clause"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "f39393f494c9a6529e2a97fadffe2ecca281d8741c9e1e2d7ef86d29fc3d1eb1"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "37f7212ae928eb238cd0b3951cfeb98adf13419355bf2a766142df4c8447c464"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "dea58d1b2b6710d06da1656b3b308fd4fe8ecf0e8a55aae3191da7a891293975"
    sha256 cellar: :any_skip_relocation, sonoma:         "cf758395a955a5678460ca49855b9d29121e9210c6be663f2d5904f90f613a98"
    sha256 cellar: :any_skip_relocation, ventura:        "e496a2fe51c3b67c84842aaef935c697afb7854380189f5f979dc06b70a2f1ec"
    sha256 cellar: :any_skip_relocation, monterey:       "2fc7fb1ad18b6bbf12eed76c4a7dada743317c9151d5b1e500574953393126b3"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "5b33af6e354030af45aeb9c5162ffd652a130fc04b1cedc0c61e430103857ee2"
  end

  depends_on "python@3.12"

  resource "build" do
    url "https://files.pythonhosted.org/packages/98/e3/83a89a9d338317f05a68c86a2bbc9af61235bc55a0c6a749d37598fb2af1/build-1.0.3.tar.gz"
    sha256 "538aab1b64f9828977f84bc63ae570b060a8ed1be419e7870b8b4fc5e6ea553b"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/96/d3/f04c7bfcf5c1862a2a5b845c6b2b360488cf47af55dfa79c98f6a6bf98b5/click-8.1.7.tar.gz"
    sha256 "ca9853ad459e787e2192211578cc907e7594e294c7ccc834310722b41b9ca6de"
  end

  resource "packaging" do
    url "https://files.pythonhosted.org/packages/fb/2b/9b9c33ffed44ee921d0967086d653047286054117d584f1b1a7c22ceaf7b/packaging-23.2.tar.gz"
    sha256 "048fb0e9405036518eaaf48a55953c750c11e1a1b68e0dd1a9d62ed0c092cfc5"
  end

  resource "pyproject-hooks" do
    url "https://files.pythonhosted.org/packages/25/c1/374304b8407d3818f7025457b7366c8e07768377ce12edfe2aa58aa0f64c/pyproject_hooks-1.0.0.tar.gz"
    sha256 "f271b298b97f5955d53fb12b72c1fb1948c22c1a6b70b315c54cedaca0264ef5"
  end

  resource "setuptools" do
    url "https://files.pythonhosted.org/packages/c9/3d/74c56f1c9efd7353807f8f5fa22adccdba99dc72f34311c30a69627a0fad/setuptools-69.1.0.tar.gz"
    sha256 "850894c4195f09c4ed30dba56213bf7c3f21d86ed6bdaafb5df5972593bfc401"
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/b0/b4/bc2baae3970c282fae6c2cb8e0f179923dceb7eaffb0e76170628f9af97b/wheel-0.42.0.tar.gz"
    sha256 "c45be39f7882c9d34243236f2d63cbd58039e360f85d0913425fbd7ceea617a8"
  end

  def install
    virtualenv_install_with_resources

    %w[pip-compile pip-sync].each do |script|
      generate_completions_from_executable(bin/script, shells: [:fish, :zsh], shell_parameter_format: :click)
    end
  end

  test do
    (testpath/"requirements.in").write <<~EOS
      pip-tools
      typing-extensions
    EOS

    compiled = shell_output("#{bin}/pip-compile requirements.in -q -o -")
    assert_match "This file is autogenerated by pip-compile", compiled
    assert_match "# via pip-tools", compiled
  end
end