cask "font-cormorant" do
  version "3.609"
  sha256 "e394546eec6dfdfc235b667b00bbc5b4b6144110d6ed1810fc3570098a4fba7b"

  url "https:github.comCatharsisFontsCormorantreleasesdownloadv#{version}Cormorant_Install_v#{version}.zip"
  name "Cormorant"
  homepage "https:github.comCatharsisFontsCormorant"

  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-Bold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-BoldItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-Italic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-Light.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-LightItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-Medium.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-MediumItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-Regular.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-SemiBold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorant-SemiBoldItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-Bold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-BoldItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-Italic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-Light.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-LightItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-Medium.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-MediumItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-Regular.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-SemiBold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantGaramond-SemiBoldItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-Bold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-BoldItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-Italic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-Light.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-LightItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-Medium.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-MediumItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-Regular.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-SemiBold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantInfant-SemiBoldItalic.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantSC-Bold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantSC-Light.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantSC-Medium.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantSC-Regular.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantSC-SemiBold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUnicase-Bold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUnicase-Light.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUnicase-Medium.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUnicase-Regular.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUnicase-SemiBold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUpright-Bold.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUpright-Light.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUpright-Medium.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUpright-Regular.ttf"
  font "Cormorant_Install_v#{version}1. TrueType Font FilesCormorantUpright-SemiBold.ttf"

  # No zap stanza required
end