cask "font-hk-grotesk" do
  version "1.0"
  sha256 "750e49b186c09e971d51e9831d252402b8d086df7492885a6cbdf1834e98217a"

  url "https://www.fontsquirrel.com/fonts/download/hk-grotesk",
      verified: "www.fontsquirrel.com"
  name "HK Grotesk"
  desc "HK Grotesk font family"
  homepage "https://hanken.co/product/hk-grotesk/"

  font "HKGrotesk-Bold.otf"
  font "HKGrotesk-BoldItalic.otf"
  font "HKGrotesk-BoldLegacy.otf"
  font "HKGrotesk-BoldLegacyItalic.otf"
  font "HKGrotesk-Italic.otf"
  font "HKGrotesk-LegacyItalic.otf"
  font "HKGrotesk-Light.otf"
  font "HKGrotesk-LightItalic.otf"
  font "HKGrotesk-LightLegacy.otf"
  font "HKGrotesk-LightLegacyItalic.otf"
  font "HKGrotesk-Medium.otf"
  font "HKGrotesk-MediumItalic.otf"
  font "HKGrotesk-MediumLegacy.otf"
  font "HKGrotesk-MediumLegacyItalic.otf"
  font "HKGrotesk-Regular.otf"
  font "HKGrotesk-RegularLegacy.otf"
  font "HKGrotesk-SemiBold.otf"
  font "HKGrotesk-SemiBoldItalic.otf"
  font "HKGrotesk-SemiBoldLegacy.otf"
  font "HKGrotesk-SemiBoldLegacyItalic.otf"
end