cask "font-urbanist" do
  version "1.321"
  sha256 "43b9c601884e3d348016444d34c5d55ac3381d18fdbe9644432be50305fa54c3"

  url "https:github.comcoreyhuUrbanistreleasesdownloadv#{version}Urbanist-fonts.zip"
  name "Urbanist"
  homepage "https:github.comcoreyhuUrbanist"

  font "Urbanist-fontsfontsotfUrbanist-Black.otf"
  font "Urbanist-fontsfontsotfUrbanist-BlackItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-Bold.otf"
  font "Urbanist-fontsfontsotfUrbanist-BoldItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-ExtraBold.otf"
  font "Urbanist-fontsfontsotfUrbanist-ExtraBoldItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-ExtraLight.otf"
  font "Urbanist-fontsfontsotfUrbanist-ExtraLightItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-Italic.otf"
  font "Urbanist-fontsfontsotfUrbanist-Light.otf"
  font "Urbanist-fontsfontsotfUrbanist-LightItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-Medium.otf"
  font "Urbanist-fontsfontsotfUrbanist-MediumItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-Regular.otf"
  font "Urbanist-fontsfontsotfUrbanist-SemiBold.otf"
  font "Urbanist-fontsfontsotfUrbanist-SemiBoldItalic.otf"
  font "Urbanist-fontsfontsotfUrbanist-Thin.otf"
  font "Urbanist-fontsfontsotfUrbanist-ThinItalic.otf"
  font "Urbanist-fontsfontsttfUrbanist-Black.ttf"
  font "Urbanist-fontsfontsttfUrbanist-BlackItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-Bold.ttf"
  font "Urbanist-fontsfontsttfUrbanist-BoldItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-ExtraBold.ttf"
  font "Urbanist-fontsfontsttfUrbanist-ExtraBoldItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-ExtraLight.ttf"
  font "Urbanist-fontsfontsttfUrbanist-ExtraLightItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-Italic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-Light.ttf"
  font "Urbanist-fontsfontsttfUrbanist-LightItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-Medium.ttf"
  font "Urbanist-fontsfontsttfUrbanist-MediumItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-Regular.ttf"
  font "Urbanist-fontsfontsttfUrbanist-SemiBold.ttf"
  font "Urbanist-fontsfontsttfUrbanist-SemiBoldItalic.ttf"
  font "Urbanist-fontsfontsttfUrbanist-Thin.ttf"
  font "Urbanist-fontsfontsttfUrbanist-ThinItalic.ttf"
  font "Urbanist-fontsfontsvariableUrbanist-Italic[wght].ttf"
  font "Urbanist-fontsfontsvariableUrbanist[ital,wght].ttf"
  font "Urbanist-fontsfontsvariableUrbanist[wght].ttf"

  # No zap stanza required
end