cask "font-plemol-jp-nf" do
  version "1.6.0"
  sha256 "ea63ed7eb6fa255f7bd2bb1066158077d41b8668e32a86ffa9322501d6fc18dc"

  url "https:github.comyuru7PlemolJPreleasesdownloadv#{version}PlemolJP_NF_v#{version}.zip"
  name "PlemolJP NF"
  desc "Japanese programming font synthesized from IBM Plex Mono and IBM Plex Sans JP"
  homepage "https:github.comyuru7PlemolJP"

  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Bold.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-BoldItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-ExtraLight.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-ExtraLightItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Italic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Light.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-LightItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Medium.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-MediumItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Regular.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-SemiBold.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-SemiBoldItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Text.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-TextItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-Thin.ttf"
  font "PlemolJP_NF_v#{version}PlemolJPConsole_NFPlemolJPConsoleNF-ThinItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Bold.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-BoldItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-ExtraLight.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-ExtraLightItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Italic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Light.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-LightItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Medium.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-MediumItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Regular.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-SemiBold.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-SemiBoldItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Text.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-TextItalic.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-Thin.ttf"
  font "PlemolJP_NF_v#{version}PlemolJP35Console_NFPlemolJP35ConsoleNF-ThinItalic.ttf"

  # No zap stanza required
end