cask "font-barlow" do
  version "1.422"
  sha256 "91d3caad016fae2ed2ca36b472e1b740f7baebaaeb8a947cbdf70d281c03ac07"

  url "https:github.comjptbarlowarchive#{version}.zip",
      verified: "github.comjptbarlow"
  name "Barlow"
  homepage "https:tribby.comfontsbarlow"

  font "barlow-#{version}fontsotfBarlow-Black.otf"
  font "barlow-#{version}fontsotfBarlow-BlackItalic.otf"
  font "barlow-#{version}fontsotfBarlow-Bold.otf"
  font "barlow-#{version}fontsotfBarlow-BoldItalic.otf"
  font "barlow-#{version}fontsotfBarlow-ExtraBold.otf"
  font "barlow-#{version}fontsotfBarlow-ExtraBoldItalic.otf"
  font "barlow-#{version}fontsotfBarlow-ExtraLight.otf"
  font "barlow-#{version}fontsotfBarlow-ExtraLightItalic.otf"
  font "barlow-#{version}fontsotfBarlow-Italic.otf"
  font "barlow-#{version}fontsotfBarlow-Light.otf"
  font "barlow-#{version}fontsotfBarlow-LightItalic.otf"
  font "barlow-#{version}fontsotfBarlow-Medium.otf"
  font "barlow-#{version}fontsotfBarlow-MediumItalic.otf"
  font "barlow-#{version}fontsotfBarlow-Regular.otf"
  font "barlow-#{version}fontsotfBarlow-SemiBold.otf"
  font "barlow-#{version}fontsotfBarlow-SemiBoldItalic.otf"
  font "barlow-#{version}fontsotfBarlow-Thin.otf"
  font "barlow-#{version}fontsotfBarlow-ThinItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Black.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-BlackItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Bold.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-BoldItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-ExtraBold.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-ExtraBoldItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-ExtraLight.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-ExtraLightItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Italic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Light.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-LightItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Medium.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-MediumItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Regular.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-SemiBold.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-SemiBoldItalic.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-Thin.otf"
  font "barlow-#{version}fontsotfBarlowCondensed-ThinItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Black.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-BlackItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Bold.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-BoldItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-ExtraBold.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-ExtraBoldItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-ExtraLight.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-ExtraLightItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Italic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Light.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-LightItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Medium.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-MediumItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Regular.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-SemiBold.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-SemiBoldItalic.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-Thin.otf"
  font "barlow-#{version}fontsotfBarlowSemiCondensed-ThinItalic.otf"

  # No zap stanza required
end