class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://ghfast.top/https://github.com/keploy/keploy/archive/refs/tags/v3.3.52.tar.gz"
  sha256 "4a02fca10241085d4e7c418cdc3f04c2f43d69e203bfc5d94b94505ec9b3909e"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "179c2d7ecedc976da8632f179ecbcd0047ba4494a0a13fd5335ca121f63d7681"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "179c2d7ecedc976da8632f179ecbcd0047ba4494a0a13fd5335ca121f63d7681"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "179c2d7ecedc976da8632f179ecbcd0047ba4494a0a13fd5335ca121f63d7681"
    sha256 cellar: :any_skip_relocation, sonoma:        "d695aa403d21befdee5eb6bd6c1b953f585fb9d2a88f22989c7ea152a01472fb"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "62ed0f58a7bde0f9cfb33a222411a242ad74b40a74b67b798036f4e7f62460ec"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "f65f3ee087c9619cd6cc01d53b0de27ea38af1fa59e023b6c0cee22b5c7a3fed"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end