class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://ghfast.top/https://github.com/keploy/keploy/archive/refs/tags/v3.6.12.tar.gz"
  sha256 "6fcd85b3c73eee3b171a025ee8e913cbc3bae976853881c13e81034641562489"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "2bd538717e570fbffbc753be9b28c051993434fe6a29c36707ea9b3a66ac2c6a"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "2bd538717e570fbffbc753be9b28c051993434fe6a29c36707ea9b3a66ac2c6a"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "2bd538717e570fbffbc753be9b28c051993434fe6a29c36707ea9b3a66ac2c6a"
    sha256 cellar: :any_skip_relocation, sonoma:        "af00287b33a059482318c2fbb177885a2003b98d7eaf7c07805eb3b08d7a6a46"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "dfd482f11b5e757dbefc2b8a6b6caa7fd7b03ee8a1394e1c4888e0d324151b64"
    sha256 cellar: :any,                 x86_64_linux:  "0f5dc833714de8661949c5b48a065637dc1113ecaac2705fa7c219cb4117096c"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end