class Btllib < Formula
  desc "Bioinformatics Technology Lab common code library"
  homepage "https://github.com/bcgsc/btllib"
  url "https://ghfast.top/https://github.com/bcgsc/btllib/releases/download/v1.7.6/btllib-1.7.6.tar.gz"
  sha256 "36eea386e42033b8e099232ca19827cd6c70b8f92bdfe4f6ed51fc6ad976486b"
  license "GPL-3.0-or-later"

  bottle do
    sha256 cellar: :any,                 arm64_tahoe:   "4f4429b45c95bbf2721e957400277712dfe4e9aac916132f248e0dc5e57ca3e1"
    sha256 cellar: :any,                 arm64_sequoia: "a9bd0432b49338c549aef34f63ad545d20cf8ab48f729a3320f58bfd12fcc8f8"
    sha256 cellar: :any,                 arm64_sonoma:  "ebaab1487a030eb109193a24eb34b1a7521e3f66db673fbaadd8362b03936c16"
    sha256 cellar: :any,                 sonoma:        "7b4d7723956e2165c03ee6078249e265606d8c6542cae067bef2ffe237856fec"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "3971e3e8fd67fdf130c31e0580beb45e961caca8e1952bb4c01653495a75f2f5"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "fb6d4c923df2e6babe437eb6d84687402ab173f67e7541fa3ab99ee7cce3ff9d"
  end

  depends_on "cmake" => :build
  depends_on "meson" => :build
  depends_on "ninja" => :build
  depends_on "python@3.13" => :build # cxx file generated by swig is not compatible with 3.14

  on_macos do
    depends_on "libomp"
  end

  # Apply FreeBSD patch to fix build with newer Clang, https://github.com/simongog/sdsl-lite/issues/462
  patch :p0 do
    url "https://ghfast.top/https://raw.githubusercontent.com/freebsd/freebsd-ports/af74f60a871e4a5aa7aea787fc235a2cb760e764/devel/sdsl-lite/files/patch-include_sdsl_louds__tree.hpp"
    sha256 "84aef67058947044c40032ac39d9b6d1b8a285c581f660d565cd23aaa4beade7"
    directory "subprojects/sdsl-lite"
  end

  def install
    # Workaround for CMake 4 compatibility
    ENV["CMAKE_POLICY_VERSION_MINIMUM"] = "3.5"

    args = %w[-Db_ndebug=true -Db_coverage=false]
    system "meson", "setup", "build", *args, *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"
  end

  test do
    (testpath/"test.cpp").write <<~CPP
      #include "btllib/seq.hpp"

      #include <string>

      int main()
      {
        std::string seq = "ACGTACACTGGACTGAGTCT";
        std::string rc = "AGACTCAGTCCAGTGTACGT";
        if (btllib::get_reverse_complement(seq) != rc) {
          return 1;
        }
        return 0;
      }
    CPP
    system ENV.cxx, "test.cpp", "-std=c++11", "-I#{include}", "-L#{lib}", "-lbtllib", "-o", "test"
    system "./test"
  end
end