cask "font-plemol-jp-hs" do
  version "1.7.1"
  sha256 "2d88d578f6ea814ec5f5806219f5589cb7daa3608daef255ad8a54ae8f106583"

  url "https:github.comyuru7PlemolJPreleasesdownloadv#{version}PlemolJP_HS_v#{version}.zip"
  name "PlemolJP HS"
  desc "Japanese programming font synthesized from IBM Plex Mono and IBM Plex Sans JP"
  homepage "https:github.comyuru7PlemolJP"

  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Bold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Italic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Light.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Medium.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Regular.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Text.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-Thin.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP_HSPlemolJPHS-ThinItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Bold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Italic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Light.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Medium.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Regular.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Text.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-Thin.ttf"
  font "PlemolJP_HS_v#{version}PlemolJPConsole_HSPlemolJPConsoleHS-ThinItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Bold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Italic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Light.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Medium.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Regular.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Text.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-Thin.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35_HSPlemolJP35HS-ThinItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Bold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-BoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-ExtraLight.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-ExtraLightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Italic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Light.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-LightItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Medium.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-MediumItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Regular.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-SemiBold.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-SemiBoldItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Text.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-TextItalic.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-Thin.ttf"
  font "PlemolJP_HS_v#{version}PlemolJP35Console_HSPlemolJP35ConsoleHS-ThinItalic.ttf"

  # No zap stanza required
end