cask "font-plemol-jp" do
  version "2.0.4"
  sha256 "0bf19bd2a242e70582bb8c0be084c878e843f6aeaa9e00210828532285599757"

  url "https:github.comyuru7PlemolJPreleasesdownloadv#{version}PlemolJP_v#{version}.zip"
  name "PlemolJP"
  homepage "https:github.comyuru7PlemolJP"

  no_autobump! because: :requires_manual_review

  font "PlemolJP_v#{version}PlemolJPPlemolJP-Bold.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-BoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-ExtraLight.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-ExtraLightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-Italic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-Light.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-LightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-Medium.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-MediumItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-Regular.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-SemiBold.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-SemiBoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-Text.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-TextItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-Thin.ttf"
  font "PlemolJP_v#{version}PlemolJPPlemolJP-ThinItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Bold.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-BoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-ExtraLight.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-ExtraLightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Italic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Light.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-LightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Medium.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-MediumItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Regular.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-SemiBold.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-SemiBoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Text.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-TextItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-Thin.ttf"
  font "PlemolJP_v#{version}PlemolJP35PlemolJP35-ThinItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Bold.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-BoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-ExtraLight.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-ExtraLightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Italic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Light.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-LightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Medium.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-MediumItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Regular.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-SemiBold.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-SemiBoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Text.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-TextItalic.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-Thin.ttf"
  font "PlemolJP_v#{version}PlemolJP35ConsolePlemolJP35Console-ThinItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Bold.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-BoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-ExtraLight.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-ExtraLightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Italic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Light.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-LightItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Medium.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-MediumItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Regular.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-SemiBold.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-SemiBoldItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Text.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-TextItalic.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-Thin.ttf"
  font "PlemolJP_v#{version}PlemolJPConsolePlemolJPConsole-ThinItalic.ttf"

  # No zap stanza required
end