class Ucon64 < Formula
  desc "ROM backup tool and emulator's Swiss Army knife program"
  homepage "https://ucon64.sourceforge.io/"
  url "https://downloads.sourceforge.net/project/ucon64/ucon64/ucon64-2.2.2/ucon64-2.2.2-src.tar.gz"
  sha256 "e100ad4a30f6c19abde98e361c6a0ecac4e40477f54cfb75498c5ccd21fb3a18"
  license "GPL-2.0-or-later"
  head "https://svn.code.sf.net/p/ucon64/svn/trunk/ucon64"

  livecheck do
    url :stable
    regex(%r{url=.*?/ucon64[._-]v?(\d+(?:\.\d+)+)-src\.t}i)
  end

  no_autobump! because: :requires_manual_review

  bottle do
    rebuild 1
    sha256 arm64_tahoe:   "5f3fb969676e2ae50d11401a3b4da71df0a5e99adc037ba0f04fca6c9def11d7"
    sha256 arm64_sequoia: "6c441a8fc88d68888010de08d4c309e113f51d7678e61708b6210fa08fdaf851"
    sha256 arm64_sonoma:  "bbab173eda2b5b91ca4ecce4e02fe84f17f4cbefb6e6c89282ec9e9934132aea"
    sha256 sonoma:        "9ca84df8b500fbee8ca081cfd47baf5b3f3f90cdf30fa3e208ec265b093b02c9"
    sha256 arm64_linux:   "68ab6314679f0e61da877eebbeb975f14395a331897ae1c5422e8b28b1ad8682"
    sha256 x86_64_linux:  "469604929938639dcb7d0f9e5e246c4a817cbaecdbd18ae797bd6ea32394b4f6"
  end

  uses_from_macos "unzip" => [:build, :test]

  on_linux do
    depends_on "zlib-ng-compat"
  end

  def install
    # ucon64's normal install process installs the discmage library in
    # the user's home folder. We want to store it inside the prefix, so
    # we have to change the default value of ~/.ucon64rc to point to it.
    # .ucon64rc is generated by the binary, so we adjust the default that
    # is set when no .ucon64rc exists.
    inreplace "src/ucon64_misc.c", "PROPERTY_MODE_DIR (\"ucon64\") \"#{shared_library("discmage")}\"",
                                   "\"#{opt_prefix}/libexec/#{shared_library("libdiscmage")}\""

    cd "src" do
      args = ["--disable-silent-rules", "--with-libdiscmage"]
      args << "--disable-parallel" if OS.linux? && Hardware::CPU.arm? # no sys/io.h
      system "./configure", *args, *std_configure_args
      system "make"
      bin.install "ucon64"
      libexec.install "libdiscmage/#{shared_library("discmage")}" => shared_library("libdiscmage")
    end
  end

  def caveats
    <<~EOS
      You can copy/move your DAT file collection to $HOME/.ucon64/dat
      Be sure to check $HOME/.ucon64rc for configuration after running uCON64
      for the first time.
    EOS
  end

  test do
    resource "homebrew-super_bat_puncher_demo" do
      url "https://morphcat.de/superbatpuncher/Super%20Bat%20Puncher%20Demo.zip"
      sha256 "d74cb3ba11a4ef5d0f8d224325958ca1203b0d8bb4a7a79867e412d987f0b846"
    end

    resource("homebrew-super_bat_puncher_demo").stage testpath

    assert_match "00000000  4e 45 53 1a  08 00 11 00  00 00 00 00  00 00 00 00",
                 shell_output("#{bin}/ucon64 \"#{testpath}/Super Bat Puncher Demo.nes\"")
  end
end