class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https:docs.astral.shuv"
  url "https:github.comastral-shuvarchiverefstags0.7.6.tar.gz"
  sha256 "2262a7d2e12ea80e4eedf3d4048d0b474533b579c020bdc3b28ab211a9b5ae67"
  license any_of: ["Apache-2.0", "MIT"]
  head "https:github.comastral-shuv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "58b0e47143b20e7dec921f9ae3fdbfa78151bc988f11b2db5eaa64847bfc73e2"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "25328d1b86becb1fd72caf2e7bc560825cc2227f3292fbd4896072eb6be17944"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "c0a0d08c8a46e9df8079d8695e9e892d5f7bb481947f4a8ed69da11d3d2c4cb7"
    sha256 cellar: :any_skip_relocation, sonoma:        "a88050c8e763f7a38f0004fbfc20ff6dc5dd4e1fbc8c8fa611bd0a544e1c6265"
    sha256 cellar: :any_skip_relocation, ventura:       "1bcd3112762e0b7ca3655ad02b35e63a207d49adb6c4ce9caccb6d87649e827c"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "8f0ae210d4a2eefebd3b5a34343c823d2f32e51df49bb556348dfb04f6bc3fb2"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "135e8e8abc1dab603e50e927b189bdab359193849e82d7bde88a73e0d6056543"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    system "cargo", "install", "--no-default-features", *std_cargo_args(path: "cratesuv")
    generate_completions_from_executable(bin"uv", "generate-shell-completion")
    generate_completions_from_executable(bin"uvx", "--generate-shell-completion")
  end

  test do
    (testpath"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}uvx -q ruff@0.5.1 --version")
  end
end