class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://ghfast.top/https://github.com/astral-sh/uv/archive/refs/tags/0.12.21.tar.gz"
  sha256 "fc310bd92057b841b58db9e4859ec863b8a949f9e131a9928e2ff0b0a233e6f7"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "8739f34c34ddd57ffb46da9b2e704ff62643baf0ceee7642aa70115ba4e8e2a5"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "6ae8e0e699e175eaa4fac8ae9c7b00b50e2718e59e57dbdb3ece9eacd7004837"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "9746d2c068e96ccabb2e1bd81a02755fb2e02bb7e6b691a5070de2430176c12f"
    sha256 cellar: :any,                 arm64_linux:       "c1059209972c16e6b6fe3458bb3373ec6ba3de8f48d6475559e3150db366ddbb"
    sha256 cellar: :any,                 x86_64_linux:      "25135665af688e5d25271288e8ca0dd4f12618f641df9c27945ac8fc645d700f"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  # downloads wheels in test
  allow_network_access! :test

  def fetch
    system "cargo", "fetch", *std_cargo_fetch_args
  end

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end