class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://ghfast.top/https://github.com/astral-sh/uv/archive/refs/tags/0.9.9.tar.gz"
  sha256 "0b130e6c74d39ee6fd32cc5e673c5240a35a05bbfbdca9a6ab2690ac22d7c7ad"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "7c884bbe739786e735f903c91f5d91e85e9deb20012b52349f6edd1b1f128ecb"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "fda264f23c4f42a8aeffb7c461f0164f047de3934537b3f4c8575b48a6a77de8"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "fb346d5244d4078970f3972a64013935a0eacd3da6bbf4656e7d07113db7acd1"
    sha256 cellar: :any_skip_relocation, sonoma:        "33398e6cc630fde310f91049968eebcca20a47f344316b8ee36caf84e73d04de"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "1c3ac58c82ed6602ea70a643e37aef322e7f2c47429c75268ada2435be259151"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "211a88d544d7754281b6bd7d330feeec838fb49d7a2eaddf64fbeb77ec1e0249"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end