class Glib < Formula
  include Language::Python::Shebang

  desc "Core application library for C"
  homepage "https:developer.gnome.orgglib"
  url "https:download.gnome.orgsourcesglib2.78glib-2.78.3.tar.xz"
  sha256 "609801dd373796e515972bf95fc0b2daa44545481ee2f465c4f204d224b2bc21"
  license "LGPL-2.1-or-later"

  bottle do
    sha256 arm64_sonoma:   "0508a3adb74773f5cc36db72a52b206250f58e3a63038b4d839912a672f705a3"
    sha256 arm64_ventura:  "25043e7acd81017477a6125097802b9482026786037ef9ed40fcffca5ca3fcc9"
    sha256 arm64_monterey: "459ebb452eeab56e6e4343a89e9b077ebfce48d2cfb27ec9646d360ec0ee754e"
    sha256 sonoma:         "740a493df231d3dfe99c09fa27a8ad415fff7650640ae56de6249caa5d452eaf"
    sha256 ventura:        "b152fe3051632e427e1ee58e68c5627ae5291d038120765a870ffb4978109020"
    sha256 monterey:       "ce7245d82b2dd64a41c0f95ccea14a197412f2d5c479dbd0e17e0d7d7e300f67"
    sha256 x86_64_linux:   "8657e856d1ea8610a23fccaf0cfa94b3a3271986c54101b69d5734ad1f9b0807"
  end

  depends_on "gettext" => :build
  depends_on "meson" => :build
  depends_on "ninja" => :build
  depends_on "pkg-config" => :build
  depends_on "python-setuptools" => :build
  depends_on "pcre2"

  uses_from_macos "libffi", since: :catalina
  uses_from_macos "python", since: :catalina

  on_macos do
    depends_on "gettext"
  end

  on_linux do
    depends_on "dbus"
    depends_on "util-linux"
  end

  # These used to live in the now defunct `glib-utils`.
  link_overwrite "bingdbus-codegen", "binglib-genmarshal", "binglib-mkenums", "bingtester-report"
  link_overwrite "shareglib-2.0codegen", "shareglib-2.0gdb"

  # replace several hardcoded paths with homebrew counterparts
  patch do
    url "https:raw.githubusercontent.comHomebrewformula-patches43467fd8dfc0e8954892ecc08fab131242dca025glibhardcoded-paths.diff"
    sha256 "d81c9e8296ec5b53b4ead6917f174b06026eeb0c671dfffc4965b2271fb6a82c"
  end

  def install
    inreplace %w[gioxdgmimexdgmime.c glibgutils.c], "@@HOMEBREW_PREFIX@@", HOMEBREW_PREFIX
    # Avoid the sandbox violation when an empty directory is created outside of the formula prefix.
    inreplace "giomeson.build", "install_emptydir(glib_giomodulesdir)", ""

    # Disable dtrace; see https:trac.macports.orgticket30413
    # and https:gitlab.gnome.orgGNOMEglib-issues653
    args = %W[
      --default-library=both
      --localstatedir=#{var}
      -Dgio_module_dir=#{HOMEBREW_PREFIX}libgiomodules
      -Dbsymbolic_functions=false
      -Ddtrace=false
      -Druntime_dir=#{var}run
    ]

    system "meson", "setup", "build", *args, *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"

    # ensure giomoduledir contains prefix, as this pkgconfig variable will be
    # used by glib-networking and glib-openssl to determine where to install
    # their modules
    inreplace lib"pkgconfiggio-2.0.pc",
              "giomoduledir=#{HOMEBREW_PREFIX}libgiomodules",
              "giomoduledir=${libdir}giomodules"

    if OS.mac?
      # `pkg-config --libs glib-2.0` includes -lintl, and gettext itself does not
      # have a pkgconfig file, so we add gettext lib and include paths here.
      gettext = Formula["gettext"].opt_prefix
      inreplace lib"pkgconfigglib-2.0.pc" do |s|
        s.gsub! "Libs: -L${libdir} -lglib-2.0 -lintl",
                "Libs: -L${libdir} -lglib-2.0 -L#{gettext}lib -lintl"
        s.gsub! "Cflags: -I${includedir}glib-2.0 -I${libdir}glib-2.0include",
                "Cflags: -I${includedir}glib-2.0 -I${libdir}glib-2.0include -I#{gettext}include"
      end

      if MacOS.version < :catalina
        # `pkg-config --print-requires-private gobject-2.0` includes libffi,
        # but that package is keg-only so it needs to look for the pkgconfig file
        # in libffi's opt path.
        libffi = Formula["libffi"].opt_prefix
        inreplace lib"pkgconfiggobject-2.0.pc" do |s|
          s.gsub! "Requires.private: libffi",
                  "Requires.private: #{libffi}libpkgconfiglibffi.pc"
        end
      end
    end

    rm "giocompletion.gitignore"
    bash_completion.install (buildpath"giocompletion").children
    rewrite_shebang detected_python_shebang(use_python_from_path: true), *bin.children
  end

  def post_install
    (HOMEBREW_PREFIX"libgiomodules").mkpath
  end

  test do
    (testpath"test.c").write <<~EOS
      #include <string.h>
      #include <glib.h>

      int main(void)
      {
          gchar *result_1, *result_2;
          char *str = "string";

          result_1 = g_convert(str, strlen(str), "ASCII", "UTF-8", NULL, NULL, NULL);
          result_2 = g_convert(result_1, strlen(result_1), "UTF-8", "ASCII", NULL, NULL, NULL);

          return (strcmp(str, result_2) == 0) ? 0 : 1;
      }
    EOS
    system ENV.cc, "-o", "test", "test.c", "-I#{include}glib-2.0",
                   "-I#{lib}glib-2.0include", "-L#{lib}", "-lglib-2.0"
    system ".test"

    assert_match "This file is generated by glib-mkenum", shell_output("#{bin}glib-mkenums")
  end
end