class GoLibrespot < Formula
  desc "Spotify client"
  homepage "https://github.com/devgianlu/go-librespot"
  url "https://ghfast.top/https://github.com/devgianlu/go-librespot/archive/refs/tags/v0.10.3.tar.gz"
  sha256 "18546e823f5921afa6545b0a75059b2e6822ee97454b6d16f9178a9d2cf46e49"
  license "GPL-3.0-only"
  head "https://github.com/devgianlu/go-librespot.git", branch: "master"

  bottle do
    sha256 cellar: :any, arm64_golden_gate: "4c66f81d9401c9fc459765c8db99f2a9740da4f72889bd59bf0bffddd5a0ce07"
    sha256 cellar: :any, arm64_tahoe:       "5f08e1cd72a717c370d6b21ed81e5275de12f95fb0064f0d411f4dcc8a40ca9a"
    sha256 cellar: :any, arm64_sequoia:     "eb8b70590534e08dd5a3528f3ffb15bf746ca3b4a4cbb8c0cd3bd95e6804d0c4"
    sha256 cellar: :any, arm64_linux:       "af2d0dd9f308fbb2ce677b7f6de174becc355e5de7e1ba1519874be8dfe32fa7"
    sha256 cellar: :any, x86_64_linux:      "61bd9fdfb249683ec8c864cb74e253ca75b88934261ac9bd4e23fe7345009d12"
  end

  depends_on "go" => :build
  depends_on "pkgconf" => :build
  depends_on "flac"
  depends_on "libogg"
  depends_on "libvorbis"
  depends_on "mpg123"

  on_linux do
    depends_on "alsa-lib"
  end

  deny_network_access!

  def fetch
    system "go", "mod", "download"
  end

  def install
    ENV["CGO_ENABLED"] = "1" if OS.linux? && Hardware::CPU.arm?

    ldflags = %W[-X github.com/devgianlu/go-librespot.version=#{version}]
    ldflags << "-X github.com/devgianlu/go-librespot.commit=#{Utils.git_short_head(length: 8)}" if build.head?

    system "go", "build", *std_go_args(output: bin/"go-librespot", ldflags:), "./cmd/daemon"

    # On macOS, create a minimal config that selects the correct backend.
    return unless OS.mac?

    (buildpath/"config.yml").write <<~YAML
      # Auto-generated by Homebrew. You can edit this file.
      # Use CoreAudio via AudioToolbox on macOS.
      audio_backend: audio-toolbox
    YAML
    pkgetc.install "config.yml"
  end

  service do
    run [opt_bin/"go-librespot", "--config_dir", etc/"go-librespot"]
    keep_alive true
    log_path var/"log/go-librespot.log"
    error_log_path var/"log/go-librespot.log"
  end

  test do
    cfg = testpath/"config.yml"
    cfg.write <<~YAML
      volume_steps: not_a_number
    YAML

    output = shell_output("#{bin}/go-librespot --config_dir #{testpath} 2>&1", 1)
    assert_match "failed loading config", output
    assert_match "failed to unmarshal configuration", output
  end
end