class GoLibrespot < Formula
  desc "Spotify client"
  homepage "https://github.com/devgianlu/go-librespot"
  url "https://ghfast.top/https://github.com/devgianlu/go-librespot/archive/refs/tags/v0.7.3.tar.gz"
  sha256 "5df90372c5f5108fb9b13718effcddf122eb0e8ada9bd3a9014089c581d956d7"
  license "GPL-3.0-only"
  head "https://github.com/devgianlu/go-librespot.git", branch: "master"

  bottle do
    sha256 cellar: :any,                 arm64_tahoe:   "f7951004183495f564e6d11ddb6b76c204c460d6f5bff581aec1455d85f3d7ec"
    sha256 cellar: :any,                 arm64_sequoia: "18c976a6f7b4a0b4e11b2e402407dcada08f02846d02353d7610883f2fd9d81b"
    sha256 cellar: :any,                 arm64_sonoma:  "3c284fe53febbb69fac8f8014435e82638dd73ca0dbc93ca5ce4e3b7590c96e7"
    sha256 cellar: :any,                 sonoma:        "652358213dcca042ff7a4999bcf46fd23d126436de4446259c28cf19cc42a5f8"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "93e1e5c7510774a248817d6d1a2798a73b798e4bf6ad5544875b3f8f968762e5"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "3f37f34716728ab26f4cf066db34fecf85ab9437146e37133210afe93dc2a2f2"
  end

  depends_on "go" => :build
  depends_on "pkgconf" => :build
  depends_on "flac"
  depends_on "libogg"
  depends_on "libvorbis"

  on_linux do
    depends_on "alsa-lib"
  end

  def install
    ENV["CGO_ENABLED"] = "1" if OS.linux? && Hardware::CPU.arm?

    ldflags = %W[
      -s -w
      -X github.com/devgianlu/go-librespot.version=#{version}
    ]
    ldflags << "-X github.com/devgianlu/go-librespot.commit=#{Utils.git_short_head(length: 8)}" if build.head?

    system "go", "build", *std_go_args(output: bin/"go-librespot", ldflags:), "./cmd/daemon"
    (var/"log").mkpath

    # On macOS, create a minimal config that selects the correct backend.
    return unless OS.mac?

    (buildpath/"config.yml").write <<~YAML
      # Auto-generated by Homebrew. You can edit this file.
      # Use CoreAudio via AudioToolbox on macOS.
      audio_backend: audio-toolbox
    YAML
    pkgetc.install "config.yml"
  end

  service do
    run [opt_bin/"go-librespot", "--config_dir", etc/"go-librespot"]
    keep_alive true
    log_path var/"log/go-librespot.log"
    error_log_path var/"log/go-librespot.log"
  end

  test do
    cfg = testpath/"config.yml"
    cfg.write <<~YAML
      volume_steps: not_a_number
    YAML

    output = shell_output("#{bin}/go-librespot --config_dir #{testpath} 2>&1", 1)
    assert_match "failed loading config", output
    assert_match "failed to unmarshal configuration", output
  end
end