class PipTools < Formula
  include Language::Python::Virtualenv

  desc "Locking and sync for Pip requirements files"
  homepage "https://pip-tools.readthedocs.io"
  url "https://files.pythonhosted.org/packages/dd/08/76a220d1a5804bf0ad950ef3fd4894606281fc1fe674893deff795be7d91/pip-tools-7.0.0.tar.gz"
  sha256 "6a2308712727c86cc8a6cedc0e6ba01232a337c706d63926d3789462ad083d06"
  license "BSD-3-Clause"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "2ae370e3abfb0f4adc5bdcc2a7c2b12df0f7b2deb994d42e4ff6fdbb481862b4"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "fee9bdc8dfd189adabaddb3ef2d271d071719e984ef959342c429d2d401ae3e5"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "1bfc1c151cc2245158739c37de81a311701f23e9900ccbcd194108ab4732e4dd"
    sha256 cellar: :any_skip_relocation, ventura:        "fd80fea40d40888db380fe2ef75dfd0c54fec343ceae9cb0ae58208bf6dcb902"
    sha256 cellar: :any_skip_relocation, monterey:       "db705f3c12d17e1e3ef4a5d7b86c03ed484fe86d269558a2c25198e3afcf8806"
    sha256 cellar: :any_skip_relocation, big_sur:        "caf944a9938c0b88ced96d3ad4a1ae2bb76e4879dec980c402e22046e5c74814"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "7d3511f826f7165142bfd773bf6bdc1bf55974a7d64dbe47a9b15dc25cf4ee39"
  end

  depends_on "python@3.11"

  resource "build" do
    url "https://files.pythonhosted.org/packages/de/1c/fb62f81952f0e74c3fbf411261d1adbdd2d615c89a24b42d0fe44eb4bcf3/build-0.10.0.tar.gz"
    sha256 "d5b71264afdb5951d6704482aac78de887c80691c52b88a9ad195983ca2c9269"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/7e/ad/7a6a96fab480fb2fbf52f782b2deb3abe1d2c81eca3ef68a575b5a6a4f2e/click-8.1.5.tar.gz"
    sha256 "4be4b1af8d665c6d942909916d31a213a106800c47d0eeba73d34da3cbc11367"
  end

  resource "packaging" do
    url "https://files.pythonhosted.org/packages/b9/6c/7c6658d258d7971c5eb0d9b69fa9265879ec9a9158031206d47800ae2213/packaging-23.1.tar.gz"
    sha256 "a392980d2b6cffa644431898be54b0045151319d1e7ec34f0cfed48767dd334f"
  end

  resource "pyproject-hooks" do
    url "https://files.pythonhosted.org/packages/25/c1/374304b8407d3818f7025457b7366c8e07768377ce12edfe2aa58aa0f64c/pyproject_hooks-1.0.0.tar.gz"
    sha256 "f271b298b97f5955d53fb12b72c1fb1948c22c1a6b70b315c54cedaca0264ef5"
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/fc/ef/0335f7217dd1e8096a9e8383e1d472aa14717878ffe07c4772e68b6e8735/wheel-0.40.0.tar.gz"
    sha256 "cd1196f3faee2b31968d626e1731c94f99cbdb67cf5a46e4f5656cbee7738873"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    (testpath/"requirements.in").write <<~EOS
      pip-tools
      typing-extensions
    EOS

    compiled = shell_output("#{bin}/pip-compile requirements.in -q -o -")
    assert_match "This file is autogenerated by pip-compile", compiled
    assert_match "# via pip-tools", compiled
  end
end