class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://kcachegrind.github.io/"
  url "https://download.kde.org/stable/release-service/23.04.1/src/kcachegrind-23.04.1.tar.xz"
  sha256 "91d4679fb19bf1bfa2a3beb23c3f629aba2f0871dff09af144511901a26274ea"
  license "GPL-2.0-or-later"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    sha256 cellar: :any,                 arm64_ventura:  "b33c9c7acb4ae4e71b1cca93a9f9db167936ec75ae62d8e8940f9ae8e69e211e"
    sha256 cellar: :any,                 arm64_monterey: "73af3634b43eefbfe38c07a4061b3cc8cc609f06fa9514b429d070b6020169b3"
    sha256 cellar: :any,                 arm64_big_sur:  "37e792e4edb0c75a9ae15fba3c1b3ff4433b8d9d142927ada18510a7265613a2"
    sha256 cellar: :any,                 ventura:        "24dc0a608b06bbd2b9cc60a115083a8a1fc544c857711a554121f6cc01d8b1eb"
    sha256 cellar: :any,                 monterey:       "32a064f85556d045aee0c0fd52aba3f20f55d6c459bac901ce95b47e7179f7fb"
    sha256 cellar: :any,                 big_sur:        "1a2c32363aa87ff2102601220647da3bc0584ce75de240cc84fd5bf50ffaa6f4"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "691fbfd490d791d63e6798917ee42f222639f0cfceb050e0e2e049f519ce4ff4"
  end

  depends_on "graphviz"
  depends_on "qt@5"

  fails_with gcc: "5"

  def install
    args = []
    if OS.mac?
      # TODO: when using qt 6, modify the spec
      spec = (ENV.compiler == :clang) ? "macx-clang" : "macx-g++"
      args = %W[-config release -spec #{spec}]
    end

    system Formula["qt@5"].opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end
end