class Sqlc < Formula
  desc "Generate type safe Go from SQL"
  homepage "https://sqlc.dev/"
  url "https://ghproxy.com/https://github.com/kyleconroy/sqlc/archive/v1.19.0.tar.gz"
  sha256 "bdc3bd361e4d1b492bc25e4b23524633e2525db61c79b81164b218f97a141715"
  license "MIT"
  head "https://github.com/kyleconroy/sqlc.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "3bde90b912e44a7ddc99806f42a0dc4568a266dfba59dde991c4f4ae42adf2a9"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "90c64a4bb088e3a2e215936cbe455f9f70bf50b4344b711c83859670a5c6a5cd"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "d9f5ff913ce7d84ceb934d9b0f97e1679ee116dd848b430569e0993f65966130"
    sha256 cellar: :any_skip_relocation, ventura:        "64e8b013bbb9649bc18e39d2aa352baa4697a6b54368d31e0f658ad1081ad8f2"
    sha256 cellar: :any_skip_relocation, monterey:       "8a8b6422ed41fbe354eb6bb2337df7304130fd35b31c325b94540e4fca1d3523"
    sha256 cellar: :any_skip_relocation, big_sur:        "9dba11a6be48eef8406128148e91ccf961c85046443035162f616a2394084872"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "5abdfa0233e74c28eead54d74e38ae9f3f21a698b1206fb3d4cf050ae45bc1a2"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/sqlc"

    generate_completions_from_executable(bin/"sqlc", "completion")
  end

  test do
    (testpath/"sqlc.json").write <<~SQLC
      {
        "version": "1",
        "packages": [
          {
            "name": "db",
            "path": ".",
            "queries": "query.sql",
            "schema": "query.sql",
            "engine": "postgresql"
          }
        ]
      }
    SQLC

    (testpath/"query.sql").write <<~EOS
      CREATE TABLE foo (bar text);

      -- name: SelectFoo :many
      SELECT * FROM foo;
    EOS

    system bin/"sqlc", "generate"
    assert_predicate testpath/"db.go", :exist?
    assert_predicate testpath/"models.go", :exist?
    assert_match "// Code generated by sqlc. DO NOT EDIT.", File.read(testpath/"query.sql.go")
  end
end