class Libadwaita < Formula
  desc "Building blocks for modern adaptive GNOME applications"
  homepage "https://gnome.pages.gitlab.gnome.org/libadwaita/"
  url "https://download.gnome.org/sources/libadwaita/1.7/libadwaita-1.7.3.tar.xz"
  sha256 "645f8659c975f75100d2c3b4f1e9ae0ebf13052d2b87015161b3972f60b46dfa"
  license "LGPL-2.1-or-later"

  # libadwaita doesn't use GNOME's "even-numbered minor is stable" version
  # scheme. This regex is the same as the one generated by the `Gnome` strategy
  # but it's necessary to avoid the related version scheme logic.
  livecheck do
    url :stable
    regex(/libadwaita-(\d+(?:\.\d+)+)\.t/i)
  end

  bottle do
    sha256 arm64_sequoia: "3288905818dc1c1ae5de6e9a2df7e6ea29b5900f65f308eb626f7203abe907ac"
    sha256 arm64_sonoma:  "b6d9a7806c74ecc137631c89d54ea3a982a3c4a77f0dde92362d5d765de64923"
    sha256 arm64_ventura: "f03c6e291fc1cba05aefd806bfaec52e1fe28915ce0e0b91963bb2d5ac73dc39"
    sha256 sonoma:        "180b3c9a9c95d29371ba3cc115d6c8cdbddf238e1049b19895d61fdf7eab4141"
    sha256 ventura:       "6601f90c7878d5e5a986b6c69b264564608153522cb392a7ec0bcbce63b1b386"
    sha256 arm64_linux:   "0cbdc3b30d5d492fbc41c98bce06e09807dcda20dfd1cf250c5372317a9164a4"
    sha256 x86_64_linux:  "b4fd69cd183a5d4789862098d59e7a5395a5bc614eb9e2a9ed0e0f3b7c1f2513"
  end

  depends_on "gettext" => :build
  depends_on "gobject-introspection" => :build
  depends_on "meson" => :build
  depends_on "ninja" => :build
  depends_on "pkgconf" => [:build, :test]
  depends_on "sassc" => :build
  depends_on "vala" => :build

  depends_on "appstream"
  depends_on "fribidi"
  depends_on "glib"
  depends_on "graphene"
  depends_on "gtk4"
  depends_on "libsass"
  depends_on "pango"

  uses_from_macos "python" => :build

  on_macos do
    depends_on "gettext"
  end

  def install
    system "meson", "setup", "build", "-Dtests=false", *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"
  end

  test do
    (testpath/"test.c").write <<~C
      #include <adwaita.h>

      int main(int argc, char *argv[]) {
        g_autoptr (AdwApplication) app = NULL;
        app = adw_application_new ("org.example.Hello", G_APPLICATION_DEFAULT_FLAGS);
        return g_application_run (G_APPLICATION (app), argc, argv);
      }
    C
    flags = shell_output("#{Formula["pkgconf"].opt_bin}/pkgconf --cflags --libs libadwaita-1").strip.split
    system ENV.cc, "test.c", "-o", "test", *flags
    system "./test", "--help"

    # include a version check for the pkg-config files
    assert_match version.to_s, (lib/"pkgconfig/libadwaita-1.pc").read
  end
end