class Libmapper < Formula
  desc "Distributed system for media control mapping"
  homepage "http:www.libmapper.org"
  url "https:github.comlibmapperlibmapperreleasesdownload2.4.10libmapper-2.4.10.tar.gz"
  sha256 "e481912c491816359b8aca2ae0ea2b073bbe51fb6691e92d39ad848db93ed1e6"
  license "LGPL-2.1-or-later"

  bottle do
    sha256 cellar: :any,                 arm64_sonoma:   "6ec8236e499f58d361324ed30ee024e15c681aef952caff9cb52cf61798e0001"
    sha256 cellar: :any,                 arm64_ventura:  "9a54fbbd61ff1dcdc7221a38581820694c2e12ac1a151cd98f95a050f46b315a"
    sha256 cellar: :any,                 arm64_monterey: "c00d5a24a8a98961f1cad0657cd68bd426dd84a2a31dcde70b9d5c73837bc51b"
    sha256 cellar: :any,                 sonoma:         "f2d4b7818352d243ca2bfed29bc00b1f7844cb70cda75ffdccd2cf007e263c2f"
    sha256 cellar: :any,                 ventura:        "b44516bd993e77c6772be3645b05252956d4cf4f126e135d2c5a0082ae00a432"
    sha256 cellar: :any,                 monterey:       "117aad92a8af1f06e070fc3d3e6c28423419215fd4ffb8fe019cc9ad91b1cbcb"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "7fd56f3d210b17135462fc4b97d9927d7b8805ccd007bc840444a911c38ac85e"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "libtool" => :build
  depends_on "pkg-config" => :build
  depends_on "liblo"

  uses_from_macos "zlib"

  # version patch, upstream bug report, https:github.comlibmapperlibmapperissues106
  patch :DATA

  def install
    system ".configure", *std_configure_args
    system "make", "install"
  end

  test do
    (testpath"test.c").write <<~EOS
      #include <stdio.h>
      #include "mappermapper.h"
      int main() {
        printf("%s", mpr_get_version());
        return 0;
      }
    EOS
    system ENV.cc, "test.c", "-L#{lib}", "-lmapper", "-o", "test"
    assert_match version.to_s, shell_output(".test")
  end
end

__END__
diff --git aconfigure bconfigure
index be1f37f..b29fb66 100755
--- aconfigure
+++ bconfigure
@@ -1,6 +1,6 @@
 #! binsh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by GNU Autoconf 2.71 for libmapper 2.4.9.17+gf0e37ae5.
+# Generated by GNU Autoconf 2.71 for libmapper 2.4.10.
 #
 # Report bugs to <dot_mapper@googlegroups.com>.
 #
@@ -621,8 +621,8 @@ MAKEFLAGS=
 # Identity of this package.
 PACKAGE_NAME='libmapper'
 PACKAGE_TARNAME='libmapper'
-PACKAGE_VERSION='2.4.9.17+gf0e37ae5'
-PACKAGE_STRING='libmapper 2.4.9.17+gf0e37ae5'
+PACKAGE_VERSION='2.4.10'
+PACKAGE_STRING='libmapper 2.4.10'
 PACKAGE_BUGREPORT='dot_mapper@googlegroups.com'
 PACKAGE_URL='http:libmapper.org'
 
@@ -1435,7 +1435,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the AUX 3.1 sh.
   cat <<_ACEOF
-\`configure' configures libmapper 2.4.9.17+gf0e37ae5 to adapt to many kinds of systems.
+\`configure' configures libmapper 2.4.10 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -1506,7 +1506,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of libmapper 2.4.9.17+gf0e37ae5:";;
+     short | recursive ) echo "Configuration of libmapper 2.4.10:";;
    esac
   cat <<\_ACEOF
 
@@ -1644,7 +1644,7 @@ fi
 test -n "$ac_init_help" && exit $ac_status
 if $ac_init_version; then
   cat <<\_ACEOF
-libmapper configure 2.4.9.17+gf0e37ae5
+libmapper configure 2.4.10
 generated by GNU Autoconf 2.71
 
 Copyright (C) 2021 Free Software Foundation, Inc.
@@ -2043,7 +2043,7 @@ cat >config.log <<_ACEOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by libmapper $as_me 2.4.9.17+gf0e37ae5, which was
+It was created by libmapper $as_me 2.4.10, which was
 generated by GNU Autoconf 2.71.  Invocation command line was
 
   $ $0$ac_configure_args_raw
@@ -3549,7 +3549,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE='libmapper'
- VERSION='2.4.9.17+gf0e37ae5'
+ VERSION='2.4.10'
 
 
 printf "%s\n" "#define PACKAGE \"$PACKAGE\"" >>confdefs.h
@@ -20728,7 +20728,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF || ac_write_fail=1
 # report actual input values of CONFIG_FILES etc. instead of their
 # values after options handling.
 ac_log="
-This file was extended by libmapper $as_me 2.4.9.17+gf0e37ae5, which was
+This file was extended by libmapper $as_me 2.4.10, which was
 generated by GNU Autoconf 2.71.  Invocation command line was
 
   CONFIG_FILES    = $CONFIG_FILES
@@ -20801,7 +20801,7 @@ ac_cs_config_escaped=`printf "%s\n" "$ac_cs_config" | sed "s^ ; s''\\\\\\\\
 cat >>$CONFIG_STATUS <<_ACEOF || ac_write_fail=1
 ac_cs_config='$ac_cs_config_escaped'
 ac_cs_version="\\
-libmapper config.status 2.4.9.17+gf0e37ae5
+libmapper config.status 2.4.10
 configured by $0, generated by GNU Autoconf 2.71,
   with options \\"\$ac_cs_config\\"
 
@@ -22828,4 +22828,3 @@ then :
 fi
 echo "version                     " $PACKAGE_VERSION
 echo --------------------------------------------------
-