class Libshumate < Formula
  desc "Shumate is a GTK toolkit providing widgets for embedded maps"
  homepage "https://gitlab.gnome.org/GNOME/libshumate"
  url "https://download.gnome.org/sources/libshumate/1.6/libshumate-1.6.3.tar.xz"
  sha256 "fd15c91396dcd82fce3021648541aa891e71a6bddeffc03d38597580a7da8ca1"
  license "LGPL-2.1-or-later"

  # libshumate doesn't use GNOME's "even-numbered minor is stable" version
  # scheme. This regex is the same as the one generated by the `Gnome` strategy
  # but it's necessary to avoid the related version scheme logic.
  livecheck do
    url :stable
    regex(/libshumate[._-]v?(\d+(?:\.\d+)+)\.t/i)
  end

  bottle do
    sha256 cellar: :any, arm64_tahoe:   "ad058c5cdbc65db7df6fb4c40e8e535b9a0d7c07fa626135b6293f6b9b1aacf2"
    sha256 cellar: :any, arm64_sequoia: "d4a85eb10aa6ec31a2bbf141887ef42b2f7bf8a6381bc150c558f1ecd82c0d33"
    sha256 cellar: :any, arm64_sonoma:  "1b25d7b884f34b13285e48d81a831b917e04883296a29c8208aec7e8242e783f"
    sha256 cellar: :any, sonoma:        "ac2ff829afe54ce7db56a37a6a511ca16ee7e39db40cfaf010b504c9ed73cb0b"
    sha256               arm64_linux:   "3bd1f4df8649ca2596720f6e189e9f01722c4392cafd7041df429e731890907a"
    sha256               x86_64_linux:  "a8097c1a723cd865625c72677197e028fadde7b6a43fccd44a20d68618bf0f51"
  end

  depends_on "gettext" => :build
  depends_on "gobject-introspection" => :build
  depends_on "meson" => :build
  depends_on "ninja" => :build
  depends_on "pkgconf" => [:build, :test]
  depends_on "vala" => :build

  depends_on "cairo"
  depends_on "gdk-pixbuf"
  depends_on "glib"
  depends_on "graphene"
  depends_on "gtk4"
  depends_on "json-glib"
  depends_on "libsoup"
  depends_on "pango"
  depends_on "protobuf-c"
  depends_on "sqlite"

  uses_from_macos "gperf" => :build

  on_macos do
    depends_on "gettext"
  end

  def install
    system "meson", "setup", "build", "-Dgtk_doc=false", *std_meson_args
    system "meson", "compile", "-C", "build", "--verbose"
    system "meson", "install", "-C", "build"
  end

  test do
    (testpath/"test.c").write <<~C
      #include <shumate/shumate.h>

      int main(int argc, char *argv[]) {
        char version[32];
        snprintf(version, 32, "%d.%d.%d", SHUMATE_MAJOR_VERSION, SHUMATE_MINOR_VERSION, SHUMATE_MICRO_VERSION);
        return 0;
      }
    C

    flags = shell_output("#{formula_opt_bin("pkgconf")}/pkgconf --cflags --libs shumate-1.0").strip.split
    system ENV.cc, "test.c", "-o", "test", *flags
    system "./test"

    # include a version check for the pkg-config files
    assert_match version.to_s, (lib/"pkgconfig/shumate-1.0.pc").read
  end
end