class CargoSweep < Formula
  desc "Utility for cleaning up unused build files generated by Cargo"
  homepage "https://github.com/holmgr/cargo-sweep"
  url "https://ghfast.top/https://github.com/holmgr/cargo-sweep/archive/refs/tags/v0.8.0.tar.gz"
  sha256 "f35aed1b18c7852684ed98be79e68585a9322cf868d75b71f017d24a1b7e3ee9"
  license "MIT"
  head "https://github.com/holmgr/cargo-sweep.git", branch: "master"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "d6898879b0fbfae34dea047911dced41d23ed79879886559688c94e4049255d3"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "9a0c608db46539071bbb09fbb997fe699f2561ad815ad7a5eff7b5bdaa567b69"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "cfe52f10affe82206b30a9f30dfe4d6aaf71bc643395f0e52e14df646c7bc0d5"
    sha256 cellar: :any_skip_relocation, sonoma:        "93d76c136b91c6e38561e0773b714281b5f75f2cb367d9247f0cc543fd620425"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "240f0d4bc302cacba4df9931d740029669d69b28e7b475fe69c578d1d7bfdc37"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "36c2b2a5eab5851f3217b5ea39694cf3f7e58b72be8a3fb858ecfaf65502cb2c"
  end

  depends_on "rust" => :build
  depends_on "rustup" => :test

  def install
    system "cargo", "install", "--no-default-features", *std_cargo_args
  end

  test do
    assert_equal "cargo-sweep #{version}", shell_output("#{bin}/cargo-sweep -V").strip
    ENV.prepend_path "PATH", Formula["rustup"].bin
    system "rustup", "set", "profile", "minimal"
    system "rustup", "default", "beta"

    crate = testpath/"demo-crate"
    mkdir crate do
      (crate/"src/main.rs").write <<~RUST
        fn main() {
          println!("Hello BrewTestBot!");
        }
      RUST
      (crate/"Cargo.toml").write <<~TOML
        [package]
        name = "demo-crate"
        version = "0.1.0"
        license = "MIT"
      TOML

      system "cargo", "build"

      output = shell_output("cargo sweep --time 0").strip
      # test that there are some bytes cleaned
      assert_match(/^\[INFO\] Cleaned \d+\.\d+ [KMG]iB/, output)
    end
  end
end