class Crd2pulumi < Formula
  desc "Generate typed CustomResources from a Kubernetes CustomResourceDefinition"
  homepage "https://github.com/pulumi/crd2pulumi"
  url "https://ghfast.top/https://github.com/pulumi/crd2pulumi/archive/refs/tags/v1.6.2.tar.gz"
  sha256 "4a308fe9e386ef75601da5e1aa64b41ca750b2a0a0e66c6144ee3126063d98aa"
  license "Apache-2.0"
  head "https://github.com/pulumi/crd2pulumi.git", branch: "master"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "b7da0ea7695ea0d758899ac82e4587fa4e1ad4833b6ccaec37fde8f2c33109b2"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "0b96823b4f6118f679cff33334e2265f8ebe47f9143ee8517b1f4150a5255ee5"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "2cd71efb02262c0a13c361877f7c7d72aaf29129ad3e950a8408d980867da47d"
    sha256 cellar: :any_skip_relocation, sonoma:        "05d07c058146e1ab46573483cdffb215998bc5e45f09216cd87cc40c00298694"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "5bc849ec8c4e537395f8848c38b6efaa7596d8465195bee34fea13d2b08a2b15"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "79965c3032a6e4efb67fcc2222bac344808753bdc24e4c777d6c21683c20b5b9"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/pulumi/crd2pulumi/cmd.Version=#{version}")

    generate_completions_from_executable(bin/"crd2pulumi", shell_parameter_format: :cobra)
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crd2pulumi version")

    test_crd = testpath/"crd.yaml"
    test_crd.write <<~YAML
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: widgets.example.com
      spec:
        group: example.com
        names:
          kind: Widget
          plural: widgets
          singular: widget
        scope: Namespaced
        versions:
          - name: v1
            served: true
            storage: true
            schema:
              openAPIV3Schema:
                type: object
                properties:
                  spec:
                    type: object
                    properties:
                      size:
                        type: string
                      color:
                        type: string
    YAML

    # Generate TypeScript code from the CRD
    system bin/"crd2pulumi", "--nodejsPath", testpath/"typescript", test_crd, "--force"

    assert_path_exists testpath/"typescript/example/v1/widget.ts"
    assert_match "this file was generated by crd2pulumi", (testpath/"typescript/provider.ts").read

    # Generate Python code from the CRD
    system bin/"crd2pulumi", "--pythonPath", testpath/"python", "--python", test_crd
    assert_path_exists testpath/"python/pulumi_crds/example/v1/Widget.py"
    assert_match "this file was generated by crd2pulumi", (testpath/"python/pulumi_crds/provider.py").read
  end
end