class Crd2pulumi < Formula
  desc "Generate typed CustomResources from a Kubernetes CustomResourceDefinition"
  homepage "https://github.com/pulumi/crd2pulumi"
  url "https://ghfast.top/https://github.com/pulumi/crd2pulumi/archive/refs/tags/v1.6.1.tar.gz"
  sha256 "14dff554dc6b26b43d80c36f85bd8768f9361e234aa5dcb48d8579df59c58c80"
  license "Apache-2.0"
  head "https://github.com/pulumi/crd2pulumi.git", branch: "master"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "390736f4a83c23f407845ce7ce35757716472b769bee83dcde62f069ff00a46e"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "a1ed183c72738984c22e661317d46e0ecab3d42778cb7717e2416702c8cb4033"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "fbe06b9b4521bcaf695da2fb7be72a3fdbecb10c67cd1c51cd50bc3f4f0e40f9"
    sha256 cellar: :any_skip_relocation, sonoma:        "b3e9a575ef13202f6cc87a9c294e97a6ed7a0f83ef44c23d10434930a8718b0b"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "0fa027064356ef61b917229eda5aad7f5de51d51057ca576f47fc2332d5e4530"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "e818166ab902b8bd93fde2953476d23b153ccbb38211a5de2590287116e49cc2"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/pulumi/crd2pulumi/cmd.Version=#{version}")

    generate_completions_from_executable(bin/"crd2pulumi", shell_parameter_format: :cobra)
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crd2pulumi version")

    test_crd = testpath/"crd.yaml"
    test_crd.write <<~YAML
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: widgets.example.com
      spec:
        group: example.com
        names:
          kind: Widget
          plural: widgets
          singular: widget
        scope: Namespaced
        versions:
          - name: v1
            served: true
            storage: true
            schema:
              openAPIV3Schema:
                type: object
                properties:
                  spec:
                    type: object
                    properties:
                      size:
                        type: string
                      color:
                        type: string
    YAML

    # Generate TypeScript code from the CRD
    system bin/"crd2pulumi", "--nodejsPath", testpath/"typescript", test_crd, "--force"

    assert_path_exists testpath/"typescript/example/v1/widget.ts"
    assert_match "this file was generated by crd2pulumi", (testpath/"typescript/provider.ts").read

    # Generate Python code from the CRD
    system bin/"crd2pulumi", "--pythonPath", testpath/"python", "--python", test_crd
    assert_path_exists testpath/"python/pulumi_crds/example/v1/Widget.py"
    assert_match "this file was generated by crd2pulumi", (testpath/"python/pulumi_crds/provider.py").read
  end
end