class Typical < Formula
  desc "Data interchange with algebraic data types"
  homepage "https://github.com/stepchowfun/typical"
  url "https://ghfast.top/https://github.com/stepchowfun/typical/archive/refs/tags/v0.15.0.tar.gz"
  sha256 "f8d6889b6be5e6883c93732763b832147c9986539585435d64f8214d5a97e45f"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "96a6c3d8757be39a816f834f932c449d4c16bd03a4a995b385f5f5e7b68d8b2e"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "963c1fdd423d3979ea8f09fe370f2e38be8bcb1e2b2436ba8280c790c530ac8e"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "a47a173204b0f50846a34722a6d2accc2fd71bff40fccf34b549305a5a56902b"
    sha256 cellar: :any_skip_relocation, sonoma:        "643ddaceba6215b9c64ca6093498eac63a5f3eeb0ad8c59aebec5d1709d7766e"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "177f01578c6b31bc28eee6054139bfad1242302ae6ae06fbd32d38820cfa421b"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "7450e460e45f466523910f331b7f70e71d910e5fdeb9a63914b5cb38a021d757"
  end

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    (testpath/"types.t").write <<~EOS
      struct SendEmailRequest {
          to: String = 0
          subject: String = 1
          body: String = 2
      }

      choice SendEmailResponse {
          success = 0
          error: String = 1
      }
    EOS

    (testpath/"tsout").mkpath

    assert_empty shell_output("#{bin}/typical generate --rust-file types.rs --typescript-dir tsout types.t")

    generated_rust_code = (testpath/"types.rs").read
    generated_typescript_code = (testpath/"tsout/types.ts").read

    assert_match "// This file was automatically generated by Typical", generated_rust_code
    assert_match "pub struct SendEmailRequestIn", generated_rust_code
    assert_match "pub struct SendEmailRequestOut", generated_rust_code
    assert_match "pub enum SendEmailResponseIn", generated_rust_code
    assert_match "pub enum SendEmailResponseOut", generated_rust_code
    assert_match "// This file was automatically generated by Typical", generated_typescript_code
    assert_match "export type SendEmailRequestIn", generated_typescript_code
    assert_match "export type SendEmailRequestOut", generated_typescript_code
    assert_match "export type SendEmailResponseIn", generated_typescript_code
    assert_match "export type SendEmailResponseOut", generated_typescript_code
    assert_path_exists testpath/"tsout/common.ts"
  end
end