class Typical < Formula
  desc "Data interchange with algebraic data types"
  homepage "https://github.com/stepchowfun/typical"
  url "https://ghfast.top/https://github.com/stepchowfun/typical/archive/refs/tags/v0.16.0.tar.gz"
  sha256 "ccc939b15ab5ae91ab2e9fda95cce08259092dfce7a49e579f7ff9821c748871"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "1a0351aaa6841651ae83a91c1e0fc9d1facf1d5dc6ec70b2a3fe7a93d34c8902"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "51d6a28f6bb4f610f16bde8c61d1c0689e68a836d6a93dc1ae76640b75055e49"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "9a2046c6238bcf6a5f3d0da341722bc7264f7e67341be6ec952a76a11fc82699"
    sha256 cellar: :any_skip_relocation, sonoma:        "94d20db8cc44487be74a63b654dc634195ecaa6e22cdf99f88764dff4762a9b1"
    sha256 cellar: :any,                 arm64_linux:   "bfc41a42abdcadf4cb4ed6cdb64354772fb63420f821e2d93ac18ee58482b3d4"
    sha256 cellar: :any,                 x86_64_linux:  "dce479dfabfba66174890461094174d9b1891c6d5595a927a19bdf2baddd310d"
  end

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    (testpath/"types.t").write <<~EOS
      struct SendEmailRequest {
          to: String = 0
          subject: String = 1
          body: String = 2
      }

      choice SendEmailResponse {
          success = 0
          error: String = 1
      }
    EOS

    (testpath/"tsout").mkpath

    assert_empty shell_output("#{bin}/typical generate --rust-file types.rs --typescript-dir tsout types.t")

    generated_rust_code = (testpath/"types.rs").read
    generated_typescript_code = (testpath/"tsout/types.ts").read

    assert_match "// This file was automatically generated by Typical", generated_rust_code
    assert_match "pub struct SendEmailRequestIn", generated_rust_code
    assert_match "pub struct SendEmailRequestOut", generated_rust_code
    assert_match "pub enum SendEmailResponseIn", generated_rust_code
    assert_match "pub enum SendEmailResponseOut", generated_rust_code
    assert_match "// This file was automatically generated by Typical", generated_typescript_code
    assert_match "export type SendEmailRequestIn", generated_typescript_code
    assert_match "export type SendEmailRequestOut", generated_typescript_code
    assert_match "export type SendEmailResponseIn", generated_typescript_code
    assert_match "export type SendEmailResponseOut", generated_typescript_code
    assert_path_exists testpath/"tsout/common.ts"
  end
end