class Typical < Formula
  desc "Data interchange with algebraic data types"
  homepage "https://github.com/stepchowfun/typical"
  url "https://ghfast.top/https://github.com/stepchowfun/typical/archive/refs/tags/v0.14.0.tar.gz"
  sha256 "4185ada4aa1bffff60ef5acba8d99fb982cbb5b192223ea3828ba68661d9d379"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "93ac06300c95e668a63b94d092227e8cd8c1983e026450d153511f935488f4b5"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "2ff1a99b425ce6fc5ca8aebaa5a8e4a1148cd29f01c878cd9cde7b98ae5eeba1"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "eae436384fbc321046f9d846e198d7042b63f994450a2d123e48d00b55210e5a"
    sha256 cellar: :any_skip_relocation, sonoma:        "ad7a4c06eefc785c785257c236a015bbd67a56e662b796f670a14b1ccebfbbe9"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "7f7df98443fc9815c9733b412b58394f2f8f15a21712089182a1f78169b6584b"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "a0d769b5fcc0f2b907f88f79197d4d3bbabae6953fc58d34eb648176437e0a30"
  end

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    (testpath/"types.t").write <<~EOS
      struct SendEmailRequest {
          to: String = 0
          subject: String = 1
          body: String = 2
      }

      choice SendEmailResponse {
          success = 0
          error: String = 1
      }
    EOS

    (testpath/"tsout").mkpath

    assert_empty shell_output("#{bin}/typical generate --rust-file types.rs --typescript-dir tsout types.t")

    generated_rust_code = (testpath/"types.rs").read
    generated_typescript_code = (testpath/"tsout/types.ts").read

    assert_match "// This file was automatically generated by Typical", generated_rust_code
    assert_match "pub struct SendEmailRequestIn", generated_rust_code
    assert_match "pub struct SendEmailRequestOut", generated_rust_code
    assert_match "pub enum SendEmailResponseIn", generated_rust_code
    assert_match "pub enum SendEmailResponseOut", generated_rust_code
    assert_match "// This file was automatically generated by Typical", generated_typescript_code
    assert_match "export type SendEmailRequestIn", generated_typescript_code
    assert_match "export type SendEmailRequestOut", generated_typescript_code
    assert_match "export type SendEmailResponseIn", generated_typescript_code
    assert_match "export type SendEmailResponseOut", generated_typescript_code
    assert_path_exists testpath/"tsout/common.ts"
  end
end