class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://apps.kde.org/kcachegrind/"
  url "https://download.kde.org/stable/release-service/25.04.3/src/kcachegrind-25.04.3.tar.xz"
  sha256 "23c7dcbbf15c5ee00ddac068022f118b5de939d097199b0f918df9f94f74d9e1"
  license "GPL-2.0-or-later"
  head "https://invent.kde.org/sdk/kcachegrind.git", branch: "master"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    sha256 cellar: :any,                 arm64_sonoma:  "3cb9f47b1236370e7554ffbef2b1c9194b28b03e46b11e46166d806d9d70d030"
    sha256 cellar: :any,                 arm64_ventura: "ee4d1fc822fbcd8484148ab67cb6016136120555ce97a477b1001cfedcac027a"
    sha256 cellar: :any,                 sonoma:        "11ab671be2cc6f26126edd7f74aabf4cbd3a8afb3b06f877db679feb081262f3"
    sha256 cellar: :any,                 ventura:       "fb4895da49e7fed69d255383cac7eda986ccde17ade8981e4fbaefd35a892de9"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "7c3e670228ed1cafc53ca860a851e5889b134ee9864e5ec0f06764f9b1ca048b"
  end

  depends_on "graphviz"
  depends_on "qt"

  def install
    args = %w[-config release]
    if OS.mac?
      spec = (ENV.compiler == :clang) ? "macx-clang" : "macx-g++"
      args += %W[-spec #{spec}]
    end

    qt = Formula["qt"]
    system qt.opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end
end