class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://apps.kde.org/kcachegrind/"
  url "https://download.kde.org/stable/release-service/25.12.2/src/kcachegrind-25.12.2.tar.xz"
  sha256 "46e837b3ad12f9dbea68eed040219ce7e66ac58b47fc29430a1a4f93d7591b07"
  license "GPL-2.0-or-later"
  head "https://invent.kde.org/sdk/kcachegrind.git", branch: "master"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    sha256 cellar: :any,                 arm64_tahoe:   "0d2ec7b6671acdbc97125f84b4858afe78f6b1586085ceda9cb1bf977d7750da"
    sha256 cellar: :any,                 arm64_sequoia: "1bb09e576c5961adefee32f789216f3e424a0fdc2092f4ec16520a73ebc8cf79"
    sha256 cellar: :any,                 arm64_sonoma:  "ca2db4dba8151f7dd93812bd8b7ada318c61769c83d7ebc3847b51d221fc1172"
    sha256 cellar: :any,                 sonoma:        "e9ce4af4610f1f0a02e7f8befb3c75da4fee60f195d000d6ead5b989ebb8aa45"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "1f3229d472645ab672135d656c11df404e4a7d41aaf30a9100ebb26da812a515"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "42ab242d0a3179b3c2b48ff4666980ead16a24e019f8e46d9397c3cf1e3828b9"
  end

  depends_on "graphviz"
  depends_on "qtbase"

  def install
    args = %w[-config release]
    if OS.mac?
      spec = (ENV.compiler == :clang) ? "macx-clang" : "macx-g++"
      args += %W[-spec #{spec}]
    end

    qt = Formula["qtbase"]
    system qt.opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end
end