class Qcachegrind < Formula
  desc "Visualize data generated by Cachegrind and Calltree"
  homepage "https://kcachegrind.github.io/"
  url "https://download.kde.org/stable/release-service/23.08.0/src/kcachegrind-23.08.0.tar.xz"
  sha256 "7c577d3d2e7115c1461ca50f1b128996719222a19d4d102376420dcc2b510781"
  license "GPL-2.0-or-later"

  # We don't match versions like 19.07.80 or 19.07.90 where the patch number
  # is 80+ (beta) or 90+ (RC), as these aren't stable releases.
  livecheck do
    url "https://download.kde.org/stable/release-service/"
    regex(%r{href=.*?v?(\d+\.\d+\.(?:(?![89]\d)\d+)(?:\.\d+)*)/?["' >]}i)
  end

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "ac9c9110a4f00299ca75d04beaa908f658a8dcf435d4541a36cb7f231671a01f"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "6a67daaa2c287f2aaed56f00a5e644ed037f38b0dd358f191fc6594c22bd2b02"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "599a9f45fa28ca578e10b2c90710f06b893645d5d7da57be016cd45ae740b59b"
    sha256 cellar: :any_skip_relocation, ventura:        "e755506d7c90f8adc6d5b20c173884714b02b97efb9b0a3a661148ea5be4b17a"
    sha256 cellar: :any_skip_relocation, monterey:       "c2e8b234ce86f54dd900d3694701e13c8d9d94f5873667f7e61a291ff077134f"
    sha256 cellar: :any_skip_relocation, big_sur:        "4883c743258d3198d6522571537924d783a1234d85742667c4945b8dc0cb06e6"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "9c6c73f83f38e788c6b41e5e4e20cb61b232c2b638051248d9879ff6276a52e1"
  end

  depends_on "graphviz"
  depends_on "qt@5"

  fails_with gcc: "5"

  def install
    args = []
    if OS.mac?
      # TODO: when using qt 6, modify the spec
      spec = (ENV.compiler == :clang) ? "macx-clang" : "macx-g++"
      args = %W[-config release -spec #{spec}]
    end

    system Formula["qt@5"].opt_bin/"qmake", *args
    system "make"

    if OS.mac?
      prefix.install "qcachegrind/qcachegrind.app"
      bin.install_symlink prefix/"qcachegrind.app/Contents/MacOS/qcachegrind"
    else
      bin.install "qcachegrind/qcachegrind"
    end
  end
end