cask "font-recursive-desktop" do
  version "1.085"
  sha256 "cbcbdf7a0e181d284a9235e09ed5f3873e527bc5dd1d977df71cdc1ff937da02"

  url "https:github.comarrowtyperecursivereleasesdownloadv#{version}ArrowType-Recursive-#{version}.zip",
      verified: "github.comarrowtyperecursive"
  name "Recursive Desktop"
  homepage "https:www.recursive.design"

  no_autobump! because: :requires_manual_review

  font "ArrowType-Recursive-#{version}Recursive_DesktopRecursive_VF_#{version}.ttf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-BdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-Black.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-BlkItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-Bold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-ExtraBd.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-Italic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-Light.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-LtItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-Med.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-Regular.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-SemiBd.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-XBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoCslSt-XBlkItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-Black.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-BlackItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-Bold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-BoldItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-ExBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-ExtraBold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-Italic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-Light.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-LightItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-Med.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-Regular.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-SemiBold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveMonoLnrSt-XBlkItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-BdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-Black.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-BlkItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-Bold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-ExtraBd.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-Italic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-Light.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-LtItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-Med.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-Regular.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-SemiBd.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-XBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansCslSt-XBlkItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-Black.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-BlackItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-Bold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-BoldItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-ExBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-ExtraBold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-Italic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-Light.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-LightItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-Med.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-MedItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-Regular.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-SemiBold.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-SmBdItalic.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-XBlk.otf"
  font "ArrowType-Recursive-#{version}Recursive_Desktopseparate_staticsOTFRecursiveSansLnrSt-XBlkItalic.otf"

  # No zap stanza required
end