cask "font-redhat" do
  version "4.1.0"
  sha256 "c620b2b84df0f7bf8c176f74881b7614a835ed18189d28bb1a9945c74488e5b5"

  url "https:github.comRedHatOfficialRedHatFontarchiverefstags#{version}.tar.gz"
  name "Red Hat"
  homepage "https:github.comRedHatOfficialRedHatFont"

  font "RedHatFont-#{version}fontsMonootfRedHatMono-Bold.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-BoldItalic.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-Italic.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-Light.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-LightItalic.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-Medium.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-MediumItalic.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-Regular.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-SemiBold.otf"
  font "RedHatFont-#{version}fontsMonootfRedHatMono-SemiBoldItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-Black.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-BlackItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-Bold.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-BoldItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-ExtraBold.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-ExtraBoldItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-Italic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-Light.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-LightItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-Medium.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-MediumItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-Regular.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-SemiBold.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayotfRedHatDisplay-SemiBoldItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayvariableRedHatDisplayVF-Italic.ttf"
  font "RedHatFont-#{version}fontsProportionalRedHatDisplayvariableRedHatDisplayVF.ttf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-Bold.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-BoldItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-Italic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-Light.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-LightItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-Medium.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-MediumItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-Regular.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-SemiBold.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextotfRedHatText-SemiBoldItalic.otf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextvariableRedHatTextVF-Italic.ttf"
  font "RedHatFont-#{version}fontsProportionalRedHatTextvariableRedHatTextVF.ttf"

  # No zap stanza required
end