cask "font-league-mono" do
  version "2.300"
  sha256 "16bdc983aa5eb1803a3c2fbb11d15a8cfa1ce317334a61b01f0f3ab302fdcf0d"

  url "https:github.comtheleagueofleague-monoreleasesdownload#{version}LeagueMono-#{version}.tar.xz",
      verified: "github.comtheleagueofleague-mono"
  name "League Mono"
  homepage "https:www.theleagueofmoveabletype.comleague-mono"

  font "LeagueMono-#{version}staticOTFLeagueMono-Thin.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-UltraLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-Light.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-Regular.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-Medium.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-SemiBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-Bold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtraBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedThin.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedUltraLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-Condensed.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedMedium.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedSemiBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-CondensedExtraBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedThin.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedUltraLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedMedium.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedRegular.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedSemiBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-ExtendedExtraBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowThin.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowUltraLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowMedium.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowRegular.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowSemiBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-NarrowExtraBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideThin.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideUltraLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideLight.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideMedium.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideRegular.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideSemiBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideBold.otf"
  font "LeagueMono-#{version}staticOTFLeagueMono-WideExtraBold.otf"
  font "LeagueMono-#{version}variableTTFLeagueMono-VF.ttf"

  # No zap stanza required
end