cask "font-fira-sans" do
  version "4.202"
  sha256 "d86269657387f144d77ba12011124f30f423f70672e1576dc16f918bb16ddfe4"

  url "https:github.commozillaFiraarchiverefstags#{version}.tar.gz",
      verified: "github.commozillaFira"
  name "Fira Sans"
  homepage "https:mozilla.github.ioFira"

  font "Fira-#{version}otfFiraSans-BoldItalic.otf"
  font "Fira-#{version}otfFiraSans-Bold.otf"
  font "Fira-#{version}otfFiraSans-BookItalic.otf"
  font "Fira-#{version}otfFiraSans-Book.otf"
  font "Fira-#{version}otfFiraSansCondensed-BoldItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Bold.otf"
  font "Fira-#{version}otfFiraSansCondensed-BookItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Book.otf"
  font "Fira-#{version}otfFiraSansCondensed-EightItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Eight.otf"
  font "Fira-#{version}otfFiraSansCondensed-ExtraboldItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-ExtraBold.otf"
  font "Fira-#{version}otfFiraSansCondensed-ExtraLightItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-ExtraLight.otf"
  font "Fira-#{version}otfFiraSansCondensed-FourItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Four.otf"
  font "Fira-#{version}otfFiraSansCondensed-HairItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Hair.otf"
  font "Fira-#{version}otfFiraSansCondensed-HeavyItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Heavy.otf"
  font "Fira-#{version}otfFiraSansCondensed-Italic.otf"
  font "Fira-#{version}otfFiraSansCondensed-LightItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Light.otf"
  font "Fira-#{version}otfFiraSansCondensed-MediumItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Medium.otf"
  font "Fira-#{version}otfFiraSansCondensed-Regular.otf"
  font "Fira-#{version}otfFiraSansCondensed-SemiboldItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-SemiBold.otf"
  font "Fira-#{version}otfFiraSansCondensed-ThinItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Thin.otf"
  font "Fira-#{version}otfFiraSansCondensed-TwoItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-Two.otf"
  font "Fira-#{version}otfFiraSansCondensed-UltraItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-UltraLightItalic.otf"
  font "Fira-#{version}otfFiraSansCondensed-UltraLight.otf"
  font "Fira-#{version}otfFiraSansCondensed-Ultra.otf"
  font "Fira-#{version}otfFiraSans-EightItalic.otf"
  font "Fira-#{version}otfFiraSans-Eight.otf"
  font "Fira-#{version}otfFiraSans-ExtraBoldItalic.otf"
  font "Fira-#{version}otfFiraSans-ExtraBold.otf"
  font "Fira-#{version}otfFiraSans-ExtraLightItalic.otf"
  font "Fira-#{version}otfFiraSans-ExtraLight.otf"
  font "Fira-#{version}otfFiraSans-FourItalic.otf"
  font "Fira-#{version}otfFiraSans-Four.otf"
  font "Fira-#{version}otfFiraSans-HairItalic.otf"
  font "Fira-#{version}otfFiraSans-Hair.otf"
  font "Fira-#{version}otfFiraSans-HeavyItalic.otf"
  font "Fira-#{version}otfFiraSans-Heavy.otf"
  font "Fira-#{version}otfFiraSans-Italic.otf"
  font "Fira-#{version}otfFiraSans-LightItalic.otf"
  font "Fira-#{version}otfFiraSans-Light.otf"
  font "Fira-#{version}otfFiraSans-MediumItalic.otf"
  font "Fira-#{version}otfFiraSans-Medium.otf"
  font "Fira-#{version}otfFiraSans-Regular.otf"
  font "Fira-#{version}otfFiraSans-SemiBoldItalic.otf"
  font "Fira-#{version}otfFiraSans-SemiBold.otf"
  font "Fira-#{version}otfFiraSans-ThinItalic.otf"
  font "Fira-#{version}otfFiraSans-Thin.otf"
  font "Fira-#{version}otfFiraSans-TwoItalic.otf"
  font "Fira-#{version}otfFiraSans-Two.otf"
  font "Fira-#{version}otfFiraSans-UltraItalic.otf"
  font "Fira-#{version}otfFiraSans-UltraLightItalic.otf"
  font "Fira-#{version}otfFiraSans-UltraLight.otf"
  font "Fira-#{version}otfFiraSans-Ultra.otf"

  # No zap stanza required
end