cask "font-hubot-sans" do
  version "1.0.1"
  sha256 "b460d36097a5c9a3e45710cbe1554589eaa5765d7c2c88df364516f3e27159b1"

  url "https:github.comgithubhubot-sansreleasesdownloadv#{version}Hubot-Sans.zip"
  name "Hubot-Sans"
  homepage "https:github.comgithubhubot-sans"

  font "Hubot SansOTFHubotSans-Black.otf"
  font "Hubot SansOTFHubotSans-BlackItalic.otf"
  font "Hubot SansOTFHubotSans-Bold.otf"
  font "Hubot SansOTFHubotSans-BoldItalic.otf"
  font "Hubot SansOTFHubotSans-ExtraBold.otf"
  font "Hubot SansOTFHubotSans-ExtraBoldItalic.otf"
  font "Hubot SansOTFHubotSans-ExtraLight.otf"
  font "Hubot SansOTFHubotSans-ExtraLightItalic.otf"
  font "Hubot SansOTFHubotSans-Italic.otf"
  font "Hubot SansOTFHubotSans-Light.otf"
  font "Hubot SansOTFHubotSans-LightItalic.otf"
  font "Hubot SansOTFHubotSans-Medium.otf"
  font "Hubot SansOTFHubotSans-MediumItalic.otf"
  font "Hubot SansOTFHubotSans-Regular.otf"
  font "Hubot SansOTFHubotSans-SemiBold.otf"
  font "Hubot SansOTFHubotSans-SemiBoldItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-Black.otf"
  font "Hubot SansOTFHubotSansCondensed-BlackItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-Bold.otf"
  font "Hubot SansOTFHubotSansCondensed-BoldItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-ExtraBold.otf"
  font "Hubot SansOTFHubotSansCondensed-ExtraBoldItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-ExtraLight.otf"
  font "Hubot SansOTFHubotSansCondensed-ExtraLightItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-Italic.otf"
  font "Hubot SansOTFHubotSansCondensed-Light.otf"
  font "Hubot SansOTFHubotSansCondensed-LightItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-Medium.otf"
  font "Hubot SansOTFHubotSansCondensed-MediumItalic.otf"
  font "Hubot SansOTFHubotSansCondensed-Regular.otf"
  font "Hubot SansOTFHubotSansCondensed-SemiBold.otf"
  font "Hubot SansOTFHubotSansCondensed-SemiBoldItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-Black.otf"
  font "Hubot SansOTFHubotSansExpanded-BlackItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-Bold.otf"
  font "Hubot SansOTFHubotSansExpanded-BoldItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-ExtraBold.otf"
  font "Hubot SansOTFHubotSansExpanded-ExtraBoldItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-ExtraLight.otf"
  font "Hubot SansOTFHubotSansExpanded-ExtraLightItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-Italic.otf"
  font "Hubot SansOTFHubotSansExpanded-Light.otf"
  font "Hubot SansOTFHubotSansExpanded-LightItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-Medium.otf"
  font "Hubot SansOTFHubotSansExpanded-MediumItalic.otf"
  font "Hubot SansOTFHubotSansExpanded-Regular.otf"
  font "Hubot SansOTFHubotSansExpanded-SemiBold.otf"
  font "Hubot SansOTFHubotSansExpanded-SemiBoldItalic.otf"

  # No zap stanza required
end