cask "font-inter" do
  version "4.0"
  sha256 "ff970a5d4561a04f102a7cb781adbd6ac4e9b6c460914c7a101f15acb7f7d1a4"

  url "https:github.comrsmsinterreleasesdownloadv#{version}Inter-#{version}.zip",
      verified: "github.comrsmsinter"
  name "Inter"
  desc "Variable font designed for display"
  homepage "https:rsms.meinter"

  font "InterVariable-Italic.ttf"
  font "InterVariable.ttf"
  font "extrasotfInter-Black.otf"
  font "extrasotfInter-BlackItalic.otf"
  font "extrasotfInter-Bold.otf"
  font "extrasotfInter-BoldItalic.otf"
  font "extrasotfInter-ExtraBold.otf"
  font "extrasotfInter-ExtraBoldItalic.otf"
  font "extrasotfInter-ExtraLight.otf"
  font "extrasotfInter-ExtraLightItalic.otf"
  font "extrasotfInter-Italic.otf"
  font "extrasotfInter-Light.otf"
  font "extrasotfInter-LightItalic.otf"
  font "extrasotfInter-Medium.otf"
  font "extrasotfInter-MediumItalic.otf"
  font "extrasotfInter-Regular.otf"
  font "extrasotfInter-SemiBold.otf"
  font "extrasotfInter-SemiBoldItalic.otf"
  font "extrasotfInter-Thin.otf"
  font "extrasotfInter-ThinItalic.otf"
  font "extrasotfInterDisplay-Black.otf"
  font "extrasotfInterDisplay-BlackItalic.otf"
  font "extrasotfInterDisplay-Bold.otf"
  font "extrasotfInterDisplay-BoldItalic.otf"
  font "extrasotfInterDisplay-ExtraBold.otf"
  font "extrasotfInterDisplay-ExtraBoldItalic.otf"
  font "extrasotfInterDisplay-ExtraLight.otf"
  font "extrasotfInterDisplay-ExtraLightItalic.otf"
  font "extrasotfInterDisplay-Italic.otf"
  font "extrasotfInterDisplay-Light.otf"
  font "extrasotfInterDisplay-LightItalic.otf"
  font "extrasotfInterDisplay-Medium.otf"
  font "extrasotfInterDisplay-MediumItalic.otf"
  font "extrasotfInterDisplay-Regular.otf"
  font "extrasotfInterDisplay-SemiBold.otf"
  font "extrasotfInterDisplay-SemiBoldItalic.otf"
  font "extrasotfInterDisplay-Thin.otf"
  font "extrasotfInterDisplay-ThinItalic.otf"

  # No zap stanza required
end