class Dvisvgm < Formula
  desc "Fast DVI to SVG converter"
  homepage "https://dvisvgm.de"
  url "https://ghfast.top/https://github.com/mgieseki/dvisvgm/releases/download/3.6.1/dvisvgm-3.6.1.tar.gz"
  sha256 "d6aab13136de758e91530a009ace194c84d909dbdb8efa8fa5721de71ff298d8"
  license "GPL-3.0-or-later"
  revision 1

  bottle do
    sha256 cellar: :any, arm64_tahoe:   "3d504c75913809888cf7a8a147d4702ce78f4c358a7345a122124cddb3d2feb3"
    sha256 cellar: :any, arm64_sequoia: "09d6ca853a0686c642b72786193f020364f9f5084f729eaac086e406506e6a1e"
    sha256 cellar: :any, arm64_sonoma:  "2db4ad858a6a26f049e1cf72697e7db0c93d0a98258a7786afeef86091131c86"
    sha256 cellar: :any, sonoma:        "21157de79def66e80a80b7384177640a45a35eb42f27c99715ab0239f3840284"
    sha256 cellar: :any, arm64_linux:   "6ef5f92cec2ecd544e9f911777571880c1ff720b285f7cf85fdb1f2efa5236a7"
    sha256 cellar: :any, x86_64_linux:  "38ac2045863a947fa12434694125f03b3c03971a50b3958f388f6ea20e367a53"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "libtool" => :build
  depends_on "pkgconf" => :build

  depends_on "brotli"
  depends_on "freetype"
  depends_on "ghostscript"
  depends_on "potrace"
  depends_on "texlive"
  depends_on "woff2"

  on_linux do
    depends_on "zlib-ng-compat"
  end

  def install
    args = [
      "--disable-silent-rules",
      "--with-texlive=#{formula_opt_prefix("texlive")}",
    ]
    args << "--with-zlib=#{formula_opt_prefix("zlib-ng-compat")}" if OS.linux?

    system "./configure", *args, *std_configure_args
    system "make"
    system "make", "install"

    # kpathsea anchors its search paths on the running binary, which is outside texlive's tree here
    texmf = formula_opt_prefix("texlive")/"share"
    libexec.install bin/"dvisvgm"
    (bin/"dvisvgm").write_env_script libexec/"dvisvgm",
                                     TEXMFCNF:  "${TEXMFCNF:-#{texmf}/texmf-dist/web2c}",
                                     TEXMFROOT: "${TEXMFROOT:-#{texmf}}"

    pkgshare.install "tests/data/sample.dvi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dvisvgm --version")

    # Convert DVI to SVG, embedding fonts so that the texlive lookup paths are exercised
    output = shell_output("#{bin}/dvisvgm #{pkgshare}/sample.dvi 2>&1")
    refute_match "kpathsea", output
    refute_match "not found", output
    assert_match "This file was generated by dvisvgm #{version}", (testpath/"sample.svg").read
  end
end