class Dvisvgm < Formula
  desc "Fast DVI to SVG converter"
  homepage "https://dvisvgm.de"
  url "https://ghfast.top/https://github.com/mgieseki/dvisvgm/releases/download/3.6/dvisvgm-3.6.tar.gz"
  sha256 "19dac117e5a307db5f56bde03a711a96b8c6afa0a7d38a698b313fc8d42e1468"
  license "GPL-3.0-or-later"

  bottle do
    sha256 cellar: :any,                 arm64_tahoe:   "a7ea70646b8eeb5253487029ad239849cd47d86d979b17f00b8f45decee66806"
    sha256 cellar: :any,                 arm64_sequoia: "180f615716ae2f5a25c72409bbc841d6f01b78ec0b010c8c74e2b202ed49758c"
    sha256 cellar: :any,                 arm64_sonoma:  "9045969a6b7b7a85f8c38c18ea0cfafce4a8d36f91d871aecf0bc6b86c87776b"
    sha256 cellar: :any,                 sonoma:        "39b703778b45567d7e01864138cd84fea3abc3a9451cf6d0ec4d227597cd5364"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "b99ba83475efb2a7de3f77d7344fba3d7bcc591851b8d525f1965bfeb1c53753"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "f883fa99fb3fe5fd73ecf87690fcfd15a05c523559cf8aa11aee9fc63b29f344"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "libtool" => :build
  depends_on "pkgconf" => :build

  depends_on "brotli"
  depends_on "freetype"
  depends_on "ghostscript"
  depends_on "potrace"
  depends_on "texlive"
  depends_on "woff2"

  uses_from_macos "zlib"

  def install
    args = [
      "--disable-silent-rules",
      "--with-texlive=#{Formula["texlive"].opt_prefix}",
    ]
    args << "--with-zlib=#{Formula["zlib"].opt_prefix}" if OS.linux?

    system "./configure", *args, *std_configure_args
    system "make"
    system "make", "install"

    pkgshare.install "tests/data/sample.dvi"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dvisvgm --version")

    # Convert DVI to SVG
    system bin/"dvisvgm", "--no-fonts", pkgshare/"sample.dvi"
    assert_match "This file was generated by dvisvgm #{version}", (testpath/"sample.svg").read
  end
end